package app.fpp.model.views.approval;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 19 19:50:29 ICT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ApprovalForwardRejectReceiverProposalViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ActionBy {
            public Object get(ApprovalForwardRejectReceiverProposalViewRowImpl obj) {
                return obj.getActionBy();
            }

            public void put(ApprovalForwardRejectReceiverProposalViewRowImpl obj,
                            Object value) {
                obj.setActionBy((String)value);
            }
        }
        ,
        RoleName {
            public Object get(ApprovalForwardRejectReceiverProposalViewRowImpl obj) {
                return obj.getRoleName();
            }

            public void put(ApprovalForwardRejectReceiverProposalViewRowImpl obj,
                            Object value) {
                obj.setRoleName((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(ApprovalForwardRejectReceiverProposalViewRowImpl object);

        public abstract void put(ApprovalForwardRejectReceiverProposalViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ACTIONBY = AttributesEnum.ActionBy.index();
    public static final int ROLENAME = AttributesEnum.RoleName.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ApprovalForwardRejectReceiverProposalViewRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute ActionBy.
     * @return the ActionBy
     */
    public String getActionBy() {
        return (String) getAttributeInternal(ACTIONBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ActionBy.
     * @param value value to set the  ActionBy
     */
    public void setActionBy(String value) {
        setAttributeInternal(ACTIONBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RoleName.
     * @return the RoleName
     */
    public String getRoleName() {
        return (String) getAttributeInternal(ROLENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RoleName.
     * @param value value to set the  RoleName
     */
    public void setRoleName(String value) {
        setAttributeInternal(ROLENAME, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
