package app.fpp.model.views.approval;

import java.sql.ResultSet;

import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 12 14:28:52 ICT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProposalApprovalViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ProposalApprovalViewImpl() {
    }

    /**
     * Returns the bind variable value for compId.
     * @return bind variable value for compId
     */
    public String getcompId() {
        return (String)getNamedWhereClauseParam("compId");
    }

    /**
     * Sets <code>value</code> for bind variable compId.
     * @param value value to bind as compId
     */
    public void setcompId(String value) {
        setNamedWhereClauseParam("compId", value);
    }

    /**
     * Returns the bind variable value for roleName.
     * @return bind variable value for roleName
     */
    public String getroleName() {
        return (String)getNamedWhereClauseParam("roleName");
    }

    /**
     * Sets <code>value</code> for bind variable roleName.
     * @param value value to bind as roleName
     */
    public void setroleName(String value) {
        setNamedWhereClauseParam("roleName", value);
    }

    /**
     * Returns the bind variable value for userName.
     * @return bind variable value for userName
     */
    public String getuserName() {
        return (String)getNamedWhereClauseParam("userName");
    }

    /**
     * Sets <code>value</code> for bind variable userName.
     * @param value value to bind as userName
     */
    public void setuserName(String value) {
        setNamedWhereClauseParam("userName", value);
    }


}
