package app.fpp.model.views.confirmation;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 18 16:24:13 ICT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RealisasiItemPaketViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public RealisasiItemPaketViewImpl() {
    }
}
