package app.fpp.model.views.masterdata;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 29 22:03:37 ICT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RunNumPropViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public RunNumPropViewImpl() {
    }


    /**
     * Returns the bind variable value for runYear.
     * @return bind variable value for runYear
     */
    public Number getrunYear() {
        return (Number)getNamedWhereClauseParam("runYear");
    }

    /**
     * Sets <code>value</code> for bind variable runYear.
     * @param value value to bind as runYear
     */
    public void setrunYear(Number value) {
        setNamedWhereClauseParam("runYear", value);
    }

    /**
     * Returns the bind variable value for runMonth.
     * @return bind variable value for runMonth
     */
    public Number getrunMonth() {
        return (Number)getNamedWhereClauseParam("runMonth");
    }

    /**
     * Sets <code>value</code> for bind variable runMonth.
     * @param value value to bind as runMonth
     */
    public void setrunMonth(Number value) {
        setNamedWhereClauseParam("runMonth", value);
    }

    /**
     * Returns the bind variable value for userName.
     * @return bind variable value for userName
     */
    public String getuserName() {
        return (String)getNamedWhereClauseParam("userName");
    }

    /**
     * Sets <code>value</code> for bind variable userName.
     * @param value value to bind as userName
     */
    public void setuserName(String value) {
        setNamedWhereClauseParam("userName", value);
    }
}
