package app.fpp.model.views.useraccess;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 28 17:58:05 ICT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppUserAccessViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppUserAccessViewImpl() {
    }
}
