package app.fpp.model.views.promoproposal.duplicate;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 13 10:59:46 ICT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DuplicateBiayaViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        BiayaId {
            public Object get(DuplicateBiayaViewRowImpl obj) {
                return obj.getBiayaId();
            }

            public void put(DuplicateBiayaViewRowImpl obj, Object value) {
                obj.setBiayaId((Number)value);
            }
        }
        ,
        PromoProdukId {
            public Object get(DuplicateBiayaViewRowImpl obj) {
                return obj.getPromoProdukId();
            }

            public void put(DuplicateBiayaViewRowImpl obj, Object value) {
                obj.setPromoProdukId((Number)value);
            }
        }
        ,
        Descr {
            public Object get(DuplicateBiayaViewRowImpl obj) {
                return obj.getDescr();
            }

            public void put(DuplicateBiayaViewRowImpl obj, Object value) {
                obj.setDescr((String)value);
            }
        }
        ,
        BiayaNonYearly {
            public Object get(DuplicateBiayaViewRowImpl obj) {
                return obj.getBiayaNonYearly();
            }

            public void put(DuplicateBiayaViewRowImpl obj, Object value) {
                obj.setBiayaNonYearly((Number)value);
            }
        }
        ,
        BiayaYearly {
            public Object get(DuplicateBiayaViewRowImpl obj) {
                return obj.getBiayaYearly();
            }

            public void put(DuplicateBiayaViewRowImpl obj, Object value) {
                obj.setBiayaYearly((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(DuplicateBiayaViewRowImpl object);

        public abstract void put(DuplicateBiayaViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int BIAYAID = AttributesEnum.BiayaId.index();
    public static final int PROMOPRODUKID = AttributesEnum.PromoProdukId.index();
    public static final int DESCR = AttributesEnum.Descr.index();
    public static final int BIAYANONYEARLY = AttributesEnum.BiayaNonYearly.index();
    public static final int BIAYAYEARLY = AttributesEnum.BiayaYearly.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DuplicateBiayaViewRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute BiayaId.
     * @return the BiayaId
     */
    public Number getBiayaId() {
        return (Number) getAttributeInternal(BIAYAID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BiayaId.
     * @param value value to set the  BiayaId
     */
    public void setBiayaId(Number value) {
        setAttributeInternal(BIAYAID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PromoProdukId.
     * @return the PromoProdukId
     */
    public Number getPromoProdukId() {
        return (Number) getAttributeInternal(PROMOPRODUKID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PromoProdukId.
     * @param value value to set the  PromoProdukId
     */
    public void setPromoProdukId(Number value) {
        setAttributeInternal(PROMOPRODUKID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Descr.
     * @return the Descr
     */
    public String getDescr() {
        return (String) getAttributeInternal(DESCR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Descr.
     * @param value value to set the  Descr
     */
    public void setDescr(String value) {
        setAttributeInternal(DESCR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BiayaNonYearly.
     * @return the BiayaNonYearly
     */
    public Number getBiayaNonYearly() {
        return (Number) getAttributeInternal(BIAYANONYEARLY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BiayaNonYearly.
     * @param value value to set the  BiayaNonYearly
     */
    public void setBiayaNonYearly(Number value) {
        setAttributeInternal(BIAYANONYEARLY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BiayaYearly.
     * @return the BiayaYearly
     */
    public Number getBiayaYearly() {
        return (Number) getAttributeInternal(BIAYAYEARLY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BiayaYearly.
     * @param value value to set the  BiayaYearly
     */
    public void setBiayaYearly(Number value) {
        setAttributeInternal(BIAYAYEARLY, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
