package app.fpp.model.entities.budgetsetting;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 07 15:01:47 ICT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BudgetPostTranImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        BudgetPostTranId {
            public Object get(BudgetPostTranImpl obj) {
                return obj.getBudgetPostTranId();
            }

            public void put(BudgetPostTranImpl obj, Object value) {
                obj.setBudgetPostTranId((DBSequence)value);
            }
        }
        ,
        BudgetPostingId {
            public Object get(BudgetPostTranImpl obj) {
                return obj.getBudgetPostingId();
            }

            public void put(BudgetPostTranImpl obj, Object value) {
                obj.setBudgetPostingId((Number)value);
            }
        }
        ,
        BudgetType {
            public Object get(BudgetPostTranImpl obj) {
                return obj.getBudgetType();
            }

            public void put(BudgetPostTranImpl obj, Object value) {
                obj.setBudgetType((String)value);
            }
        }
        ,
        BudgetDate {
            public Object get(BudgetPostTranImpl obj) {
                return obj.getBudgetDate();
            }

            public void put(BudgetPostTranImpl obj, Object value) {
                obj.setBudgetDate((Date)value);
            }
        }
        ,
        Amount {
            public Object get(BudgetPostTranImpl obj) {
                return obj.getAmount();
            }

            public void put(BudgetPostTranImpl obj, Object value) {
                obj.setAmount((Number)value);
            }
        }
        ,
        BudgetAsToDate {
            public Object get(BudgetPostTranImpl obj) {
                return obj.getBudgetAsToDate();
            }

            public void put(BudgetPostTranImpl obj, Object value) {
                obj.setBudgetAsToDate((Number)value);
            }
        }
        ,
        CreatedBy {
            public Object get(BudgetPostTranImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(BudgetPostTranImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CreationDate {
            public Object get(BudgetPostTranImpl obj) {
                return obj.getCreationDate();
            }

            public void put(BudgetPostTranImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ModifiedBy {
            public Object get(BudgetPostTranImpl obj) {
                return obj.getModifiedBy();
            }

            public void put(BudgetPostTranImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ModifiedDate {
            public Object get(BudgetPostTranImpl obj) {
                return obj.getModifiedDate();
            }

            public void put(BudgetPostTranImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BudgetPosting {
            public Object get(BudgetPostTranImpl obj) {
                return obj.getBudgetPosting();
            }

            public void put(BudgetPostTranImpl obj, Object value) {
                obj.setBudgetPosting((BudgetPostingImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(BudgetPostTranImpl object);

        public abstract void put(BudgetPostTranImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BUDGETPOSTTRANID = AttributesEnum.BudgetPostTranId.index();
    public static final int BUDGETPOSTINGID = AttributesEnum.BudgetPostingId.index();
    public static final int BUDGETTYPE = AttributesEnum.BudgetType.index();
    public static final int BUDGETDATE = AttributesEnum.BudgetDate.index();
    public static final int AMOUNT = AttributesEnum.Amount.index();
    public static final int BUDGETASTODATE = AttributesEnum.BudgetAsToDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int BUDGETPOSTING = AttributesEnum.BudgetPosting.index();

    /**
     * This is the default constructor (do not remove).
     */
    public BudgetPostTranImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("app.fpp.model.entities.budgetsetting.BudgetPostTran");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for BudgetPostTranId, using the alias name BudgetPostTranId.
     * @return the BudgetPostTranId
     */
    public DBSequence getBudgetPostTranId() {
        return (DBSequence)getAttributeInternal(BUDGETPOSTTRANID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BudgetPostTranId.
     * @param value value to set the BudgetPostTranId
     */
    public void setBudgetPostTranId(DBSequence value) {
        setAttributeInternal(BUDGETPOSTTRANID, value);
    }

    /**
     * Gets the attribute value for BudgetPostingId, using the alias name BudgetPostingId.
     * @return the BudgetPostingId
     */
    public Number getBudgetPostingId() {
        return (Number)getAttributeInternal(BUDGETPOSTINGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BudgetPostingId.
     * @param value value to set the BudgetPostingId
     */
    public void setBudgetPostingId(Number value) {
        setAttributeInternal(BUDGETPOSTINGID, value);
    }

    /**
     * Gets the attribute value for BudgetType, using the alias name BudgetType.
     * @return the BudgetType
     */
    public String getBudgetType() {
        return (String)getAttributeInternal(BUDGETTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BudgetType.
     * @param value value to set the BudgetType
     */
    public void setBudgetType(String value) {
        setAttributeInternal(BUDGETTYPE, value);
    }

    /**
     * Gets the attribute value for BudgetDate, using the alias name BudgetDate.
     * @return the BudgetDate
     */
    public Date getBudgetDate() {
        return (Date)getAttributeInternal(BUDGETDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BudgetDate.
     * @param value value to set the BudgetDate
     */
    public void setBudgetDate(Date value) {
        setAttributeInternal(BUDGETDATE, value);
    }

    /**
     * Gets the attribute value for Amount, using the alias name Amount.
     * @return the Amount
     */
    public Number getAmount() {
        return (Number)getAttributeInternal(AMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Amount.
     * @param value value to set the Amount
     */
    public void setAmount(Number value) {
        setAttributeInternal(AMOUNT, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for ModifiedBy, using the alias name ModifiedBy.
     * @return the ModifiedBy
     */
    public String getModifiedBy() {
        return (String)getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
     * @return the ModifiedDate
     */
    public Date getModifiedDate() {
        return (Date)getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Gets the attribute value for BudgetAsToDate, using the alias name BudgetAsToDate.
     * @return the BudgetAsToDate
     */
    public Number getBudgetAsToDate() {
        return (Number)getAttributeInternal(BUDGETASTODATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BudgetAsToDate.
     * @param value value to set the BudgetAsToDate
     */
    public void setBudgetAsToDate(Number value) {
        setAttributeInternal(BUDGETASTODATE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity BudgetPostingImpl.
     */
    public BudgetPostingImpl getBudgetPosting() {
        return (BudgetPostingImpl)getAttributeInternal(BUDGETPOSTING);
    }

    /**
     * Sets <code>value</code> as the associated entity BudgetPostingImpl.
     */
    public void setBudgetPosting(BudgetPostingImpl value) {
        setAttributeInternal(BUDGETPOSTING, value);
    }


    /**
     * @param budgetPostTranId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(DBSequence budgetPostTranId) {
        return new Key(new Object[]{budgetPostTranId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        SequenceImpl seq = new SequenceImpl("BUDGET_POST_TRAN_SEQ", getDBTransaction());
        this.setBudgetPostTranId(new DBSequence(seq.getSequenceNumber()));
    }
}
