package app.fpp.model.views.confirmation.targetpr;

import app.fpp.model.entities.confirmation.targetpr.FcsPoRequisitionTempImpl;

import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.RowID;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 04 10:48:26 ICT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FcsPoRequisitionTempViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PrId {
            public Object get(FcsPoRequisitionTempViewRowImpl obj) {
                return obj.getPrId();
            }

            public void put(FcsPoRequisitionTempViewRowImpl obj,
                            Object value) {
                obj.setPrId((DBSequence)value);
            }
        }
        ,
        CreationDate {
            public Object get(FcsPoRequisitionTempViewRowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(FcsPoRequisitionTempViewRowImpl obj,
                            Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        InterfaceSourceCode {
            public Object get(FcsPoRequisitionTempViewRowImpl obj) {
                return obj.getInterfaceSourceCode();
            }

            public void put(FcsPoRequisitionTempViewRowImpl obj,
                            Object value) {
                obj.setInterfaceSourceCode((String)value);
            }
        }
        ,
        SourceTypeCode {
            public Object get(FcsPoRequisitionTempViewRowImpl obj) {
                return obj.getSourceTypeCode();
            }

            public void put(FcsPoRequisitionTempViewRowImpl obj,
                            Object value) {
                obj.setSourceTypeCode((String)value);
            }
        }
        ,
        RequisitionType {
            public Object get(FcsPoRequisitionTempViewRowImpl obj) {
                return obj.getRequisitionType();
            }

            public void put(FcsPoRequisitionTempViewRowImpl obj,
                            Object value) {
                obj.setRequisitionType((String)value);
            }
        }
        ,
        DestinationTypeCode {
            public Object get(FcsPoRequisitionTempViewRowImpl obj) {
                return obj.getDestinationTypeCode();
            }

            public void put(FcsPoRequisitionTempViewRowImpl obj,
                            Object value) {
                obj.setDestinationTypeCode((String)value);
            }
        }
        ,
        UnitPrice {
            public Object get(FcsPoRequisitionTempViewRowImpl obj) {
                return obj.getUnitPrice();
            }

            public void put(FcsPoRequisitionTempViewRowImpl obj,
                            Object value) {
                obj.setUnitPrice((Number)value);
            }
        }
        ,
        AuthorizationStatus {
            public Object get(FcsPoRequisitionTempViewRowImpl obj) {
                return obj.getAuthorizationStatus();
            }

            public void put(FcsPoRequisitionTempViewRowImpl obj,
                            Object value) {
                obj.setAuthorizationStatus((String)value);
            }
        }
        ,
        BatchId {
            public Object get(FcsPoRequisitionTempViewRowImpl obj) {
                return obj.getBatchId();
            }

            public void put(FcsPoRequisitionTempViewRowImpl obj,
                            Object value) {
                obj.setBatchId((Number)value);
            }
        }
        ,
        GroupCode {
            public Object get(FcsPoRequisitionTempViewRowImpl obj) {
                return obj.getGroupCode();
            }

            public void put(FcsPoRequisitionTempViewRowImpl obj,
                            Object value) {
                obj.setGroupCode((String)value);
            }
        }
        ,
        ApprovalPathId {
            public Object get(FcsPoRequisitionTempViewRowImpl obj) {
                return obj.getApprovalPathId();
            }

            public void put(FcsPoRequisitionTempViewRowImpl obj,
                            Object value) {
                obj.setApprovalPathId((Number)value);
            }
        }
        ,
        PreparerName {
            public Object get(FcsPoRequisitionTempViewRowImpl obj) {
                return obj.getPreparerName();
            }

            public void put(FcsPoRequisitionTempViewRowImpl obj,
                            Object value) {
                obj.setPreparerName((String)value);
            }
        }
        ,
        ReqNumberSegment1 {
            public Object get(FcsPoRequisitionTempViewRowImpl obj) {
                return obj.getReqNumberSegment1();
            }

            public void put(FcsPoRequisitionTempViewRowImpl obj,
                            Object value) {
                obj.setReqNumberSegment1((String)value);
            }
        }
        ,
        HeaderAttribute1 {
            public Object get(FcsPoRequisitionTempViewRowImpl obj) {
                return obj.getHeaderAttribute1();
            }

            public void put(FcsPoRequisitionTempViewRowImpl obj,
                            Object value) {
                obj.setHeaderAttribute1((String)value);
            }
        }
        ,
        HeaderAttribute2 {
            public Object get(FcsPoRequisitionTempViewRowImpl obj) {
                return obj.getHeaderAttribute2();
            }

            public void put(FcsPoRequisitionTempViewRowImpl obj,
                            Object value) {
                obj.setHeaderAttribute2((String)value);
            }
        }
        ,
        HeaderAttribute3 {
            public Object get(FcsPoRequisitionTempViewRowImpl obj) {
                return obj.getHeaderAttribute3();
            }

            public void put(FcsPoRequisitionTempViewRowImpl obj,
                            Object value) {
                obj.setHeaderAttribute3((String)value);
            }
        }
        ,
        HeaderAttribute4 {
            public Object get(FcsPoRequisitionTempViewRowImpl obj) {
                return obj.getHeaderAttribute4();
            }

            public void put(FcsPoRequisitionTempViewRowImpl obj,
                            Object value) {
                obj.setHeaderAttribute4((String)value);
            }
        }
        ,
        ItemSegment1 {
            public Object get(FcsPoRequisitionTempViewRowImpl obj) {
                return obj.getItemSegment1();
            }

            public void put(FcsPoRequisitionTempViewRowImpl obj,
                            Object value) {
                obj.setItemSegment1((String)value);
            }
        }
        ,
        UnitOfMeasure {
            public Object get(FcsPoRequisitionTempViewRowImpl obj) {
                return obj.getUnitOfMeasure();
            }

            public void put(FcsPoRequisitionTempViewRowImpl obj,
                            Object value) {
                obj.setUnitOfMeasure((String)value);
            }
        }
        ,
        UomCode {
            public Object get(FcsPoRequisitionTempViewRowImpl obj) {
                return obj.getUomCode();
            }

            public void put(FcsPoRequisitionTempViewRowImpl obj,
                            Object value) {
                obj.setUomCode((String)value);
            }
        }
        ,
        Quantity {
            public Object get(FcsPoRequisitionTempViewRowImpl obj) {
                return obj.getQuantity();
            }

            public void put(FcsPoRequisitionTempViewRowImpl obj,
                            Object value) {
                obj.setQuantity((Number)value);
            }
        }
        ,
        LineType {
            public Object get(FcsPoRequisitionTempViewRowImpl obj) {
                return obj.getLineType();
            }

            public void put(FcsPoRequisitionTempViewRowImpl obj,
                            Object value) {
                obj.setLineType((String)value);
            }
        }
        ,
        NoteToReceiver {
            public Object get(FcsPoRequisitionTempViewRowImpl obj) {
                return obj.getNoteToReceiver();
            }

            public void put(FcsPoRequisitionTempViewRowImpl obj,
                            Object value) {
                obj.setNoteToReceiver((String)value);
            }
        }
        ,
        DestinationOrganizationCode {
            public Object get(FcsPoRequisitionTempViewRowImpl obj) {
                return obj.getDestinationOrganizationCode();
            }

            public void put(FcsPoRequisitionTempViewRowImpl obj,
                            Object value) {
                obj.setDestinationOrganizationCode((String)value);
            }
        }
        ,
        DestinationSubinventory {
            public Object get(FcsPoRequisitionTempViewRowImpl obj) {
                return obj.getDestinationSubinventory();
            }

            public void put(FcsPoRequisitionTempViewRowImpl obj,
                            Object value) {
                obj.setDestinationSubinventory((String)value);
            }
        }
        ,
        DeliverToLocationCode {
            public Object get(FcsPoRequisitionTempViewRowImpl obj) {
                return obj.getDeliverToLocationCode();
            }

            public void put(FcsPoRequisitionTempViewRowImpl obj,
                            Object value) {
                obj.setDeliverToLocationCode((String)value);
            }
        }
        ,
        DeliverToRequestorName {
            public Object get(FcsPoRequisitionTempViewRowImpl obj) {
                return obj.getDeliverToRequestorName();
            }

            public void put(FcsPoRequisitionTempViewRowImpl obj,
                            Object value) {
                obj.setDeliverToRequestorName((String)value);
            }
        }
        ,
        DistributionAttribute1 {
            public Object get(FcsPoRequisitionTempViewRowImpl obj) {
                return obj.getDistributionAttribute1();
            }

            public void put(FcsPoRequisitionTempViewRowImpl obj,
                            Object value) {
                obj.setDistributionAttribute1((String)value);
            }
        }
        ,
        OrgId {
            public Object get(FcsPoRequisitionTempViewRowImpl obj) {
                return obj.getOrgId();
            }

            public void put(FcsPoRequisitionTempViewRowImpl obj,
                            Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        LineNum {
            public Object get(FcsPoRequisitionTempViewRowImpl obj) {
                return obj.getLineNum();
            }

            public void put(FcsPoRequisitionTempViewRowImpl obj,
                            Object value) {
                obj.setLineNum((Number)value);
            }
        }
        ,
        Status {
            public Object get(FcsPoRequisitionTempViewRowImpl obj) {
                return obj.getStatus();
            }

            public void put(FcsPoRequisitionTempViewRowImpl obj,
                            Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        LineAttribute2 {
            public Object get(FcsPoRequisitionTempViewRowImpl obj) {
                return obj.getLineAttribute2();
            }

            public void put(FcsPoRequisitionTempViewRowImpl obj,
                            Object value) {
                obj.setLineAttribute2((String)value);
            }
        }
        ,
        Revision {
            public Object get(FcsPoRequisitionTempViewRowImpl obj) {
                return obj.getRevision();
            }

            public void put(FcsPoRequisitionTempViewRowImpl obj,
                            Object value) {
                obj.setRevision((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(FcsPoRequisitionTempViewRowImpl object);

        public abstract void put(FcsPoRequisitionTempViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PRID = AttributesEnum.PrId.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int INTERFACESOURCECODE = AttributesEnum.InterfaceSourceCode.index();
    public static final int SOURCETYPECODE = AttributesEnum.SourceTypeCode.index();
    public static final int REQUISITIONTYPE = AttributesEnum.RequisitionType.index();
    public static final int DESTINATIONTYPECODE = AttributesEnum.DestinationTypeCode.index();
    public static final int UNITPRICE = AttributesEnum.UnitPrice.index();
    public static final int AUTHORIZATIONSTATUS = AttributesEnum.AuthorizationStatus.index();
    public static final int BATCHID = AttributesEnum.BatchId.index();
    public static final int GROUPCODE = AttributesEnum.GroupCode.index();
    public static final int APPROVALPATHID = AttributesEnum.ApprovalPathId.index();
    public static final int PREPARERNAME = AttributesEnum.PreparerName.index();
    public static final int REQNUMBERSEGMENT1 = AttributesEnum.ReqNumberSegment1.index();
    public static final int HEADERATTRIBUTE1 = AttributesEnum.HeaderAttribute1.index();
    public static final int HEADERATTRIBUTE2 = AttributesEnum.HeaderAttribute2.index();
    public static final int HEADERATTRIBUTE3 = AttributesEnum.HeaderAttribute3.index();
    public static final int HEADERATTRIBUTE4 = AttributesEnum.HeaderAttribute4.index();
    public static final int ITEMSEGMENT1 = AttributesEnum.ItemSegment1.index();
    public static final int UNITOFMEASURE = AttributesEnum.UnitOfMeasure.index();
    public static final int UOMCODE = AttributesEnum.UomCode.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int LINETYPE = AttributesEnum.LineType.index();
    public static final int NOTETORECEIVER = AttributesEnum.NoteToReceiver.index();
    public static final int DESTINATIONORGANIZATIONCODE = AttributesEnum.DestinationOrganizationCode.index();
    public static final int DESTINATIONSUBINVENTORY = AttributesEnum.DestinationSubinventory.index();
    public static final int DELIVERTOLOCATIONCODE = AttributesEnum.DeliverToLocationCode.index();
    public static final int DELIVERTOREQUESTORNAME = AttributesEnum.DeliverToRequestorName.index();
    public static final int DISTRIBUTIONATTRIBUTE1 = AttributesEnum.DistributionAttribute1.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int LINENUM = AttributesEnum.LineNum.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int LINEATTRIBUTE2 = AttributesEnum.LineAttribute2.index();
    public static final int REVISION = AttributesEnum.Revision.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FcsPoRequisitionTempViewRowImpl() {
    }

    /**
     * Gets FcsPoRequisitionTemp entity object.
     * @return the FcsPoRequisitionTemp
     */
    public FcsPoRequisitionTempImpl getFcsPoRequisitionTemp() {
        return (FcsPoRequisitionTempImpl)getEntity(0);
    }


    /**
     * Gets the attribute value for PR_ID using the alias name PrId.
     * @return the PR_ID
     */
    public DBSequence getPrId() {
        return (DBSequence)getAttributeInternal(PRID);
    }

    /**
     * Sets <code>value</code> as attribute value for PR_ID using the alias name PrId.
     * @param value value to set the PR_ID
     */
    public void setPrId(DBSequence value) {
        setAttributeInternal(PRID, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for INTERFACE_SOURCE_CODE using the alias name InterfaceSourceCode.
     * @return the INTERFACE_SOURCE_CODE
     */
    public String getInterfaceSourceCode() {
        return (String) getAttributeInternal(INTERFACESOURCECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for INTERFACE_SOURCE_CODE using the alias name InterfaceSourceCode.
     * @param value value to set the INTERFACE_SOURCE_CODE
     */
    public void setInterfaceSourceCode(String value) {
        setAttributeInternal(INTERFACESOURCECODE, value);
    }

    /**
     * Gets the attribute value for SOURCE_TYPE_CODE using the alias name SourceTypeCode.
     * @return the SOURCE_TYPE_CODE
     */
    public String getSourceTypeCode() {
        return (String) getAttributeInternal(SOURCETYPECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for SOURCE_TYPE_CODE using the alias name SourceTypeCode.
     * @param value value to set the SOURCE_TYPE_CODE
     */
    public void setSourceTypeCode(String value) {
        setAttributeInternal(SOURCETYPECODE, value);
    }

    /**
     * Gets the attribute value for REQUISITION_TYPE using the alias name RequisitionType.
     * @return the REQUISITION_TYPE
     */
    public String getRequisitionType() {
        return (String) getAttributeInternal(REQUISITIONTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for REQUISITION_TYPE using the alias name RequisitionType.
     * @param value value to set the REQUISITION_TYPE
     */
    public void setRequisitionType(String value) {
        setAttributeInternal(REQUISITIONTYPE, value);
    }

    /**
     * Gets the attribute value for DESTINATION_TYPE_CODE using the alias name DestinationTypeCode.
     * @return the DESTINATION_TYPE_CODE
     */
    public String getDestinationTypeCode() {
        return (String) getAttributeInternal(DESTINATIONTYPECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for DESTINATION_TYPE_CODE using the alias name DestinationTypeCode.
     * @param value value to set the DESTINATION_TYPE_CODE
     */
    public void setDestinationTypeCode(String value) {
        setAttributeInternal(DESTINATIONTYPECODE, value);
    }

    /**
     * Gets the attribute value for UNIT_PRICE using the alias name UnitPrice.
     * @return the UNIT_PRICE
     */
    public Number getUnitPrice() {
        return (Number) getAttributeInternal(UNITPRICE);
    }

    /**
     * Sets <code>value</code> as attribute value for UNIT_PRICE using the alias name UnitPrice.
     * @param value value to set the UNIT_PRICE
     */
    public void setUnitPrice(Number value) {
        setAttributeInternal(UNITPRICE, value);
    }

    /**
     * Gets the attribute value for AUTHORIZATION_STATUS using the alias name AuthorizationStatus.
     * @return the AUTHORIZATION_STATUS
     */
    public String getAuthorizationStatus() {
        return (String) getAttributeInternal(AUTHORIZATIONSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for AUTHORIZATION_STATUS using the alias name AuthorizationStatus.
     * @param value value to set the AUTHORIZATION_STATUS
     */
    public void setAuthorizationStatus(String value) {
        setAttributeInternal(AUTHORIZATIONSTATUS, value);
    }

    /**
     * Gets the attribute value for BATCH_ID using the alias name BatchId.
     * @return the BATCH_ID
     */
    public Number getBatchId() {
        return (Number) getAttributeInternal(BATCHID);
    }

    /**
     * Sets <code>value</code> as attribute value for BATCH_ID using the alias name BatchId.
     * @param value value to set the BATCH_ID
     */
    public void setBatchId(Number value) {
        setAttributeInternal(BATCHID, value);
    }

    /**
     * Gets the attribute value for GROUP_CODE using the alias name GroupCode.
     * @return the GROUP_CODE
     */
    public String getGroupCode() {
        return (String) getAttributeInternal(GROUPCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for GROUP_CODE using the alias name GroupCode.
     * @param value value to set the GROUP_CODE
     */
    public void setGroupCode(String value) {
        setAttributeInternal(GROUPCODE, value);
    }

    /**
     * Gets the attribute value for APPROVAL_PATH_ID using the alias name ApprovalPathId.
     * @return the APPROVAL_PATH_ID
     */
    public Number getApprovalPathId() {
        return (Number) getAttributeInternal(APPROVALPATHID);
    }

    /**
     * Sets <code>value</code> as attribute value for APPROVAL_PATH_ID using the alias name ApprovalPathId.
     * @param value value to set the APPROVAL_PATH_ID
     */
    public void setApprovalPathId(Number value) {
        setAttributeInternal(APPROVALPATHID, value);
    }

    /**
     * Gets the attribute value for PREPARER_NAME using the alias name PreparerName.
     * @return the PREPARER_NAME
     */
    public String getPreparerName() {
        return (String) getAttributeInternal(PREPARERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for PREPARER_NAME using the alias name PreparerName.
     * @param value value to set the PREPARER_NAME
     */
    public void setPreparerName(String value) {
        setAttributeInternal(PREPARERNAME, value);
    }

    /**
     * Gets the attribute value for REQ_NUMBER_SEGMENT1 using the alias name ReqNumberSegment1.
     * @return the REQ_NUMBER_SEGMENT1
     */
    public String getReqNumberSegment1() {
        return (String) getAttributeInternal(REQNUMBERSEGMENT1);
    }

    /**
     * Sets <code>value</code> as attribute value for REQ_NUMBER_SEGMENT1 using the alias name ReqNumberSegment1.
     * @param value value to set the REQ_NUMBER_SEGMENT1
     */
    public void setReqNumberSegment1(String value) {
        setAttributeInternal(REQNUMBERSEGMENT1, value);
    }

    /**
     * Gets the attribute value for HEADER_ATTRIBUTE1 using the alias name HeaderAttribute1.
     * @return the HEADER_ATTRIBUTE1
     */
    public String getHeaderAttribute1() {
        return (String) getAttributeInternal(HEADERATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for HEADER_ATTRIBUTE1 using the alias name HeaderAttribute1.
     * @param value value to set the HEADER_ATTRIBUTE1
     */
    public void setHeaderAttribute1(String value) {
        setAttributeInternal(HEADERATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for HEADER_ATTRIBUTE2 using the alias name HeaderAttribute2.
     * @return the HEADER_ATTRIBUTE2
     */
    public String getHeaderAttribute2() {
        return (String) getAttributeInternal(HEADERATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for HEADER_ATTRIBUTE2 using the alias name HeaderAttribute2.
     * @param value value to set the HEADER_ATTRIBUTE2
     */
    public void setHeaderAttribute2(String value) {
        setAttributeInternal(HEADERATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for HEADER_ATTRIBUTE3 using the alias name HeaderAttribute3.
     * @return the HEADER_ATTRIBUTE3
     */
    public String getHeaderAttribute3() {
        return (String) getAttributeInternal(HEADERATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for HEADER_ATTRIBUTE3 using the alias name HeaderAttribute3.
     * @param value value to set the HEADER_ATTRIBUTE3
     */
    public void setHeaderAttribute3(String value) {
        setAttributeInternal(HEADERATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for HEADER_ATTRIBUTE4 using the alias name HeaderAttribute4.
     * @return the HEADER_ATTRIBUTE4
     */
    public String getHeaderAttribute4() {
        return (String) getAttributeInternal(HEADERATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for HEADER_ATTRIBUTE4 using the alias name HeaderAttribute4.
     * @param value value to set the HEADER_ATTRIBUTE4
     */
    public void setHeaderAttribute4(String value) {
        setAttributeInternal(HEADERATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ITEM_SEGMENT1 using the alias name ItemSegment1.
     * @return the ITEM_SEGMENT1
     */
    public String getItemSegment1() {
        return (String) getAttributeInternal(ITEMSEGMENT1);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_SEGMENT1 using the alias name ItemSegment1.
     * @param value value to set the ITEM_SEGMENT1
     */
    public void setItemSegment1(String value) {
        setAttributeInternal(ITEMSEGMENT1, value);
    }

    /**
     * Gets the attribute value for UNIT_OF_MEASURE using the alias name UnitOfMeasure.
     * @return the UNIT_OF_MEASURE
     */
    public String getUnitOfMeasure() {
        return (String) getAttributeInternal(UNITOFMEASURE);
    }

    /**
     * Sets <code>value</code> as attribute value for UNIT_OF_MEASURE using the alias name UnitOfMeasure.
     * @param value value to set the UNIT_OF_MEASURE
     */
    public void setUnitOfMeasure(String value) {
        setAttributeInternal(UNITOFMEASURE, value);
    }

    /**
     * Gets the attribute value for UOM_CODE using the alias name UomCode.
     * @return the UOM_CODE
     */
    public String getUomCode() {
        return (String) getAttributeInternal(UOMCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for UOM_CODE using the alias name UomCode.
     * @param value value to set the UOM_CODE
     */
    public void setUomCode(String value) {
        setAttributeInternal(UOMCODE, value);
    }

    /**
     * Gets the attribute value for QUANTITY using the alias name Quantity.
     * @return the QUANTITY
     */
    public Number getQuantity() {
        return (Number) getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for QUANTITY using the alias name Quantity.
     * @param value value to set the QUANTITY
     */
    public void setQuantity(Number value) {
        setAttributeInternal(QUANTITY, value);
    }

    /**
     * Gets the attribute value for LINE_TYPE using the alias name LineType.
     * @return the LINE_TYPE
     */
    public String getLineType() {
        return (String) getAttributeInternal(LINETYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_TYPE using the alias name LineType.
     * @param value value to set the LINE_TYPE
     */
    public void setLineType(String value) {
        setAttributeInternal(LINETYPE, value);
    }

    /**
     * Gets the attribute value for NOTE_TO_RECEIVER using the alias name NoteToReceiver.
     * @return the NOTE_TO_RECEIVER
     */
    public String getNoteToReceiver() {
        return (String) getAttributeInternal(NOTETORECEIVER);
    }

    /**
     * Sets <code>value</code> as attribute value for NOTE_TO_RECEIVER using the alias name NoteToReceiver.
     * @param value value to set the NOTE_TO_RECEIVER
     */
    public void setNoteToReceiver(String value) {
        setAttributeInternal(NOTETORECEIVER, value);
    }

    /**
     * Gets the attribute value for DESTINATION_ORGANIZATION_CODE using the alias name DestinationOrganizationCode.
     * @return the DESTINATION_ORGANIZATION_CODE
     */
    public String getDestinationOrganizationCode() {
        return (String) getAttributeInternal(DESTINATIONORGANIZATIONCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for DESTINATION_ORGANIZATION_CODE using the alias name DestinationOrganizationCode.
     * @param value value to set the DESTINATION_ORGANIZATION_CODE
     */
    public void setDestinationOrganizationCode(String value) {
        setAttributeInternal(DESTINATIONORGANIZATIONCODE, value);
    }

    /**
     * Gets the attribute value for DESTINATION_SUBINVENTORY using the alias name DestinationSubinventory.
     * @return the DESTINATION_SUBINVENTORY
     */
    public String getDestinationSubinventory() {
        return (String) getAttributeInternal(DESTINATIONSUBINVENTORY);
    }

    /**
     * Sets <code>value</code> as attribute value for DESTINATION_SUBINVENTORY using the alias name DestinationSubinventory.
     * @param value value to set the DESTINATION_SUBINVENTORY
     */
    public void setDestinationSubinventory(String value) {
        setAttributeInternal(DESTINATIONSUBINVENTORY, value);
    }

    /**
     * Gets the attribute value for DELIVER_TO_LOCATION_CODE using the alias name DeliverToLocationCode.
     * @return the DELIVER_TO_LOCATION_CODE
     */
    public String getDeliverToLocationCode() {
        return (String) getAttributeInternal(DELIVERTOLOCATIONCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for DELIVER_TO_LOCATION_CODE using the alias name DeliverToLocationCode.
     * @param value value to set the DELIVER_TO_LOCATION_CODE
     */
    public void setDeliverToLocationCode(String value) {
        setAttributeInternal(DELIVERTOLOCATIONCODE, value);
    }

    /**
     * Gets the attribute value for DELIVER_TO_REQUESTOR_NAME using the alias name DeliverToRequestorName.
     * @return the DELIVER_TO_REQUESTOR_NAME
     */
    public String getDeliverToRequestorName() {
        return (String) getAttributeInternal(DELIVERTOREQUESTORNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for DELIVER_TO_REQUESTOR_NAME using the alias name DeliverToRequestorName.
     * @param value value to set the DELIVER_TO_REQUESTOR_NAME
     */
    public void setDeliverToRequestorName(String value) {
        setAttributeInternal(DELIVERTOREQUESTORNAME, value);
    }

    /**
     * Gets the attribute value for DISTRIBUTION_ATTRIBUTE1 using the alias name DistributionAttribute1.
     * @return the DISTRIBUTION_ATTRIBUTE1
     */
    public String getDistributionAttribute1() {
        return (String) getAttributeInternal(DISTRIBUTIONATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for DISTRIBUTION_ATTRIBUTE1 using the alias name DistributionAttribute1.
     * @param value value to set the DISTRIBUTION_ATTRIBUTE1
     */
    public void setDistributionAttribute1(String value) {
        setAttributeInternal(DISTRIBUTIONATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public Number getOrgId() {
        return (Number) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for LINE_NUM using the alias name LineNum.
     * @return the LINE_NUM
     */
    public Number getLineNum() {
        return (Number) getAttributeInternal(LINENUM);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_NUM using the alias name LineNum.
     * @param value value to set the LINE_NUM
     */
    public void setLineNum(Number value) {
        setAttributeInternal(LINENUM, value);
    }


    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for LINE_ATTRIBUTE2 using the alias name LineAttribute2.
     * @return the LINE_ATTRIBUTE2
     */
    public String getLineAttribute2() {
        return (String) getAttributeInternal(LINEATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_ATTRIBUTE2 using the alias name LineAttribute2.
     * @param value value to set the LINE_ATTRIBUTE2
     */
    public void setLineAttribute2(String value) {
        setAttributeInternal(LINEATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for REVISION using the alias name Revision.
     * @return the REVISION
     */
    public Number getRevision() {
        return (Number) getAttributeInternal(REVISION);
    }

    /**
     * Sets <code>value</code> as attribute value for REVISION using the alias name Revision.
     * @param value value to set the REVISION
     */
    public void setRevision(Number value) {
        setAttributeInternal(REVISION, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
