package app.fpp.model.views.confirmation.targetpr;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 22 14:41:41 ICT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ItemBjpFlagViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ItemBjpFlagViewImpl() {
    }

    /**
     * Returns the bind variable value for orgName.
     * @return bind variable value for orgName
     */
    public String getorgName() {
        return (String)getNamedWhereClauseParam("orgName");
    }

    /**
     * Sets <code>value</code> for bind variable orgName.
     * @param value value to bind as orgName
     */
    public void setorgName(String value) {
        setNamedWhereClauseParam("orgName", value);
    }
}
