package app.fpp.model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 12 10:27:58 ICT 2017
// ---------------------------------------------------------------------
public interface ApprovalAM extends ApplicationModule {
    void setLoginToSession_ApprovalAM(String key, String val);

    void approveDocApproval(String propId, String docNo, String docStatus,
                            String promoDtFrom, String promoDtTo,
                            String docRegion, String usrRole, String userNm,
                            String aprvlCodeRun, String idDocAprvl,
                            String reasonDocAprvl, String usrAction,
                            String propDt);

    void rejectDocApproval(String propId, String docNo, String docStatus,
                           String promoDtFrom, String promoDtTo,
                           String docRegion, String usrRole, String userNm,
                           String aprvlCodeRun, String idDocAprvl,
                           String reasonDocAprvl, String usrAction,
                           String propDt);

    void forwardDocApproval(String propId, String docNo, String docStatus,
                            String promoDtFrom, String promoDtTo,
                            String docRegion, String usrRole, String userNm,
                            String aprvlCodeRun, String idDocAprvl,
                            String reasonDocAprvl, String usrAction,
                            String propDt);

    void rejectFwdDocApproval(String propId, String docNo, String docStatus,
                              String promoDtFrom, String promoDtTo,
                              String docRegion, String usrRole, String userNm,
                              String aprvlCodeRun, String idDocAprvl,
                              String reasonDocAprvl, String usrAction,
                              String propDt);
}
