package app.fpp.model.views.confirmation.modifier;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.RowID;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 23 18:56:32 ICT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FcsQpModifierTempExclViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ListHeaderId {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getListHeaderId();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setListHeaderId((Number)value);
            }
        }
        ,
        ListTypeCode {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getListTypeCode();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setListTypeCode((String)value);
            }
        }
        ,
        ModifierType {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getModifierType();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setModifierType((String)value);
            }
        }
        ,
        Name {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getName();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setName((String)value);
            }
        }
        ,
        Description {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getDescription();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        Currency {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getCurrency();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setCurrency((String)value);
            }
        }
        ,
        StartDate {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getStartDate();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setStartDate((Date)value);
            }
        }
        ,
        EndDate {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getEndDate();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setEndDate((Date)value);
            }
        }
        ,
        Active {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getActive();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setActive((String)value);
            }
        }
        ,
        Automatic {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getAutomatic();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setAutomatic((String)value);
            }
        }
        ,
        Version {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getVersion();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setVersion((Number)value);
            }
        }
        ,
        Attribute2 {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        ListLineId {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getListLineId();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setListLineId((Number)value);
            }
        }
        ,
        LineNo {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getLineNo();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setLineNo((Number)value);
            }
        }
        ,
        ListLineTypeCode {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getListLineTypeCode();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setListLineTypeCode((String)value);
            }
        }
        ,
        LineLevel {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getLineLevel();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setLineLevel((String)value);
            }
        }
        ,
        LineCode {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getLineCode();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setLineCode((String)value);
            }
        }
        ,
        LineType {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getLineType();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setLineType((String)value);
            }
        }
        ,
        StartDateLine {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getStartDateLine();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setStartDateLine((Date)value);
            }
        }
        ,
        EndDateLine {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getEndDateLine();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setEndDateLine((Date)value);
            }
        }
        ,
        AutomaticLine {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getAutomaticLine();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setAutomaticLine((String)value);
            }
        }
        ,
        PricingPhaseId {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getPricingPhaseId();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setPricingPhaseId((Number)value);
            }
        }
        ,
        PricingPhase {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getPricingPhase();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setPricingPhase((String)value);
            }
        }
        ,
        Bucket {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getBucket();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setBucket((String)value);
            }
        }
        ,
        ProductAttributeCode {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getProductAttributeCode();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setProductAttributeCode((String)value);
            }
        }
        ,
        ProductAttribute {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getProductAttribute();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setProductAttribute((String)value);
            }
        }
        ,
        ProductAttributeValueId {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getProductAttributeValueId();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setProductAttributeValueId((Number)value);
            }
        }
        ,
        ProductAttributeValue {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getProductAttributeValue();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setProductAttributeValue((String)value);
            }
        }
        ,
        ProductPrecedence {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getProductPrecedence();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setProductPrecedence((Number)value);
            }
        }
        ,
        VolumeType {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getVolumeType();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setVolumeType((String)value);
            }
        }
        ,
        BreakType {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getBreakType();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setBreakType((String)value);
            }
        }
        ,
        Uom {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getUom();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setUom((String)value);
            }
        }
        ,
        ValueFrom {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getValueFrom();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setValueFrom((String)value);
            }
        }
        ,
        ValueTo {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getValueTo();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setValueTo((String)value);
            }
        }
        ,
        ApplicationMethod {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getApplicationMethod();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setApplicationMethod((String)value);
            }
        }
        ,
        Value {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getValue();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setValue((Number)value);
            }
        }
        ,
        GroupingNo {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getGroupingNo();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setGroupingNo((Number)value);
            }
        }
        ,
        QualifierContext {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getQualifierContext();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setQualifierContext((String)value);
            }
        }
        ,
        QualifierAttr {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getQualifierAttr();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setQualifierAttr((String)value);
            }
        }
        ,
        QualifierAttrId {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getQualifierAttrId();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setQualifierAttrId((String)value);
            }
        }
        ,
        QualifierPrecedence {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getQualifierPrecedence();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setQualifierPrecedence((Number)value);
            }
        }
        ,
        Operator1 {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getOperator1();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setOperator1((String)value);
            }
        }
        ,
        QValueFrom {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getQValueFrom();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setQValueFrom((String)value);
            }
        }
        ,
        QValueTo {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getQValueTo();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setQValueTo((String)value);
            }
        }
        ,
        StartDateQualifier {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getStartDateQualifier();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setStartDateQualifier((Date)value);
            }
        }
        ,
        EndDateQualifier {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getEndDateQualifier();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setEndDateQualifier((Date)value);
            }
        }
        ,
        Flag {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getFlag();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setFlag((String)value);
            }
        }
        ,
        Message {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getMessage();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setMessage((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        UpdatedDate {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getUpdatedDate();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setUpdatedDate((Date)value);
            }
        }
        ,
        RowID {
            public Object get(FcsQpModifierTempExclViewRowImpl obj) {
                return obj.getRowID();
            }

            public void put(FcsQpModifierTempExclViewRowImpl obj,
                            Object value) {
                obj.setRowID((RowID)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(FcsQpModifierTempExclViewRowImpl object);

        public abstract void put(FcsQpModifierTempExclViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int LISTHEADERID = AttributesEnum.ListHeaderId.index();
    public static final int LISTTYPECODE = AttributesEnum.ListTypeCode.index();
    public static final int MODIFIERTYPE = AttributesEnum.ModifierType.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int CURRENCY = AttributesEnum.Currency.index();
    public static final int STARTDATE = AttributesEnum.StartDate.index();
    public static final int ENDDATE = AttributesEnum.EndDate.index();
    public static final int ACTIVE = AttributesEnum.Active.index();
    public static final int AUTOMATIC = AttributesEnum.Automatic.index();
    public static final int VERSION = AttributesEnum.Version.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int LISTLINEID = AttributesEnum.ListLineId.index();
    public static final int LINENO = AttributesEnum.LineNo.index();
    public static final int LISTLINETYPECODE = AttributesEnum.ListLineTypeCode.index();
    public static final int LINELEVEL = AttributesEnum.LineLevel.index();
    public static final int LINECODE = AttributesEnum.LineCode.index();
    public static final int LINETYPE = AttributesEnum.LineType.index();
    public static final int STARTDATELINE = AttributesEnum.StartDateLine.index();
    public static final int ENDDATELINE = AttributesEnum.EndDateLine.index();
    public static final int AUTOMATICLINE = AttributesEnum.AutomaticLine.index();
    public static final int PRICINGPHASEID = AttributesEnum.PricingPhaseId.index();
    public static final int PRICINGPHASE = AttributesEnum.PricingPhase.index();
    public static final int BUCKET = AttributesEnum.Bucket.index();
    public static final int PRODUCTATTRIBUTECODE = AttributesEnum.ProductAttributeCode.index();
    public static final int PRODUCTATTRIBUTE = AttributesEnum.ProductAttribute.index();
    public static final int PRODUCTATTRIBUTEVALUEID = AttributesEnum.ProductAttributeValueId.index();
    public static final int PRODUCTATTRIBUTEVALUE = AttributesEnum.ProductAttributeValue.index();
    public static final int PRODUCTPRECEDENCE = AttributesEnum.ProductPrecedence.index();
    public static final int VOLUMETYPE = AttributesEnum.VolumeType.index();
    public static final int BREAKTYPE = AttributesEnum.BreakType.index();
    public static final int UOM = AttributesEnum.Uom.index();
    public static final int VALUEFROM = AttributesEnum.ValueFrom.index();
    public static final int VALUETO = AttributesEnum.ValueTo.index();
    public static final int APPLICATIONMETHOD = AttributesEnum.ApplicationMethod.index();
    public static final int VALUE = AttributesEnum.Value.index();
    public static final int GROUPINGNO = AttributesEnum.GroupingNo.index();
    public static final int QUALIFIERCONTEXT = AttributesEnum.QualifierContext.index();
    public static final int QUALIFIERATTR = AttributesEnum.QualifierAttr.index();
    public static final int QUALIFIERATTRID = AttributesEnum.QualifierAttrId.index();
    public static final int QUALIFIERPRECEDENCE = AttributesEnum.QualifierPrecedence.index();
    public static final int OPERATOR1 = AttributesEnum.Operator1.index();
    public static final int QVALUEFROM = AttributesEnum.QValueFrom.index();
    public static final int QVALUETO = AttributesEnum.QValueTo.index();
    public static final int STARTDATEQUALIFIER = AttributesEnum.StartDateQualifier.index();
    public static final int ENDDATEQUALIFIER = AttributesEnum.EndDateQualifier.index();
    public static final int FLAG = AttributesEnum.Flag.index();
    public static final int MESSAGE = AttributesEnum.Message.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int UPDATEDDATE = AttributesEnum.UpdatedDate.index();
    public static final int ROWID = AttributesEnum.RowID.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FcsQpModifierTempExclViewRowImpl() {
    }

    /**
     * Gets FcsQpModifierTempExcl entity object.
     * @return the FcsQpModifierTempExcl
     */
    public EntityImpl getFcsQpModifierTempExcl() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for LIST_HEADER_ID using the alias name ListHeaderId.
     * @return the LIST_HEADER_ID
     */
    public Number getListHeaderId() {
        return (Number) getAttributeInternal(LISTHEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for LIST_HEADER_ID using the alias name ListHeaderId.
     * @param value value to set the LIST_HEADER_ID
     */
    public void setListHeaderId(Number value) {
        setAttributeInternal(LISTHEADERID, value);
    }

    /**
     * Gets the attribute value for LIST_TYPE_CODE using the alias name ListTypeCode.
     * @return the LIST_TYPE_CODE
     */
    public String getListTypeCode() {
        return (String) getAttributeInternal(LISTTYPECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for LIST_TYPE_CODE using the alias name ListTypeCode.
     * @param value value to set the LIST_TYPE_CODE
     */
    public void setListTypeCode(String value) {
        setAttributeInternal(LISTTYPECODE, value);
    }

    /**
     * Gets the attribute value for MODIFIER_TYPE using the alias name ModifierType.
     * @return the MODIFIER_TYPE
     */
    public String getModifierType() {
        return (String) getAttributeInternal(MODIFIERTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIER_TYPE using the alias name ModifierType.
     * @param value value to set the MODIFIER_TYPE
     */
    public void setModifierType(String value) {
        setAttributeInternal(MODIFIERTYPE, value);
    }

    /**
     * Gets the attribute value for NAME using the alias name Name.
     * @return the NAME
     */
    public String getName() {
        return (String) getAttributeInternal(NAME);
    }

    /**
     * Sets <code>value</code> as attribute value for NAME using the alias name Name.
     * @param value value to set the NAME
     */
    public void setName(String value) {
        setAttributeInternal(NAME, value);
    }

    /**
     * Gets the attribute value for DESCRIPTION using the alias name Description.
     * @return the DESCRIPTION
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCRIPTION using the alias name Description.
     * @param value value to set the DESCRIPTION
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for CURRENCY using the alias name Currency.
     * @return the CURRENCY
     */
    public String getCurrency() {
        return (String) getAttributeInternal(CURRENCY);
    }

    /**
     * Sets <code>value</code> as attribute value for CURRENCY using the alias name Currency.
     * @param value value to set the CURRENCY
     */
    public void setCurrency(String value) {
        setAttributeInternal(CURRENCY, value);
    }

    /**
     * Gets the attribute value for START_DATE using the alias name StartDate.
     * @return the START_DATE
     */
    public Date getStartDate() {
        return (Date) getAttributeInternal(STARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for START_DATE using the alias name StartDate.
     * @param value value to set the START_DATE
     */
    public void setStartDate(Date value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**
     * Gets the attribute value for END_DATE using the alias name EndDate.
     * @return the END_DATE
     */
    public Date getEndDate() {
        return (Date) getAttributeInternal(ENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for END_DATE using the alias name EndDate.
     * @param value value to set the END_DATE
     */
    public void setEndDate(Date value) {
        setAttributeInternal(ENDDATE, value);
    }

    /**
     * Gets the attribute value for ACTIVE using the alias name Active.
     * @return the ACTIVE
     */
    public String getActive() {
        return (String) getAttributeInternal(ACTIVE);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTIVE using the alias name Active.
     * @param value value to set the ACTIVE
     */
    public void setActive(String value) {
        setAttributeInternal(ACTIVE, value);
    }

    /**
     * Gets the attribute value for AUTOMATIC using the alias name Automatic.
     * @return the AUTOMATIC
     */
    public String getAutomatic() {
        return (String) getAttributeInternal(AUTOMATIC);
    }

    /**
     * Sets <code>value</code> as attribute value for AUTOMATIC using the alias name Automatic.
     * @param value value to set the AUTOMATIC
     */
    public void setAutomatic(String value) {
        setAttributeInternal(AUTOMATIC, value);
    }

    /**
     * Gets the attribute value for VERSION using the alias name Version.
     * @return the VERSION
     */
    public Number getVersion() {
        return (Number) getAttributeInternal(VERSION);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION using the alias name Version.
     * @param value value to set the VERSION
     */
    public void setVersion(Number value) {
        setAttributeInternal(VERSION, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for LIST_LINE_ID using the alias name ListLineId.
     * @return the LIST_LINE_ID
     */
    public Number getListLineId() {
        return (Number) getAttributeInternal(LISTLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for LIST_LINE_ID using the alias name ListLineId.
     * @param value value to set the LIST_LINE_ID
     */
    public void setListLineId(Number value) {
        setAttributeInternal(LISTLINEID, value);
    }

    /**
     * Gets the attribute value for LINE_NO using the alias name LineNo.
     * @return the LINE_NO
     */
    public Number getLineNo() {
        return (Number) getAttributeInternal(LINENO);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_NO using the alias name LineNo.
     * @param value value to set the LINE_NO
     */
    public void setLineNo(Number value) {
        setAttributeInternal(LINENO, value);
    }

    /**
     * Gets the attribute value for LIST_LINE_TYPE_CODE using the alias name ListLineTypeCode.
     * @return the LIST_LINE_TYPE_CODE
     */
    public String getListLineTypeCode() {
        return (String) getAttributeInternal(LISTLINETYPECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for LIST_LINE_TYPE_CODE using the alias name ListLineTypeCode.
     * @param value value to set the LIST_LINE_TYPE_CODE
     */
    public void setListLineTypeCode(String value) {
        setAttributeInternal(LISTLINETYPECODE, value);
    }

    /**
     * Gets the attribute value for LINE_LEVEL using the alias name LineLevel.
     * @return the LINE_LEVEL
     */
    public String getLineLevel() {
        return (String) getAttributeInternal(LINELEVEL);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_LEVEL using the alias name LineLevel.
     * @param value value to set the LINE_LEVEL
     */
    public void setLineLevel(String value) {
        setAttributeInternal(LINELEVEL, value);
    }

    /**
     * Gets the attribute value for LINE_CODE using the alias name LineCode.
     * @return the LINE_CODE
     */
    public String getLineCode() {
        return (String) getAttributeInternal(LINECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_CODE using the alias name LineCode.
     * @param value value to set the LINE_CODE
     */
    public void setLineCode(String value) {
        setAttributeInternal(LINECODE, value);
    }

    /**
     * Gets the attribute value for LINE_TYPE using the alias name LineType.
     * @return the LINE_TYPE
     */
    public String getLineType() {
        return (String) getAttributeInternal(LINETYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_TYPE using the alias name LineType.
     * @param value value to set the LINE_TYPE
     */
    public void setLineType(String value) {
        setAttributeInternal(LINETYPE, value);
    }

    /**
     * Gets the attribute value for START_DATE_LINE using the alias name StartDateLine.
     * @return the START_DATE_LINE
     */
    public Date getStartDateLine() {
        return (Date) getAttributeInternal(STARTDATELINE);
    }

    /**
     * Sets <code>value</code> as attribute value for START_DATE_LINE using the alias name StartDateLine.
     * @param value value to set the START_DATE_LINE
     */
    public void setStartDateLine(Date value) {
        setAttributeInternal(STARTDATELINE, value);
    }

    /**
     * Gets the attribute value for END_DATE_LINE using the alias name EndDateLine.
     * @return the END_DATE_LINE
     */
    public Date getEndDateLine() {
        return (Date) getAttributeInternal(ENDDATELINE);
    }

    /**
     * Sets <code>value</code> as attribute value for END_DATE_LINE using the alias name EndDateLine.
     * @param value value to set the END_DATE_LINE
     */
    public void setEndDateLine(Date value) {
        setAttributeInternal(ENDDATELINE, value);
    }

    /**
     * Gets the attribute value for AUTOMATIC_LINE using the alias name AutomaticLine.
     * @return the AUTOMATIC_LINE
     */
    public String getAutomaticLine() {
        return (String) getAttributeInternal(AUTOMATICLINE);
    }

    /**
     * Sets <code>value</code> as attribute value for AUTOMATIC_LINE using the alias name AutomaticLine.
     * @param value value to set the AUTOMATIC_LINE
     */
    public void setAutomaticLine(String value) {
        setAttributeInternal(AUTOMATICLINE, value);
    }

    /**
     * Gets the attribute value for PRICING_PHASE_ID using the alias name PricingPhaseId.
     * @return the PRICING_PHASE_ID
     */
    public Number getPricingPhaseId() {
        return (Number) getAttributeInternal(PRICINGPHASEID);
    }

    /**
     * Sets <code>value</code> as attribute value for PRICING_PHASE_ID using the alias name PricingPhaseId.
     * @param value value to set the PRICING_PHASE_ID
     */
    public void setPricingPhaseId(Number value) {
        setAttributeInternal(PRICINGPHASEID, value);
    }

    /**
     * Gets the attribute value for PRICING_PHASE using the alias name PricingPhase.
     * @return the PRICING_PHASE
     */
    public String getPricingPhase() {
        return (String) getAttributeInternal(PRICINGPHASE);
    }

    /**
     * Sets <code>value</code> as attribute value for PRICING_PHASE using the alias name PricingPhase.
     * @param value value to set the PRICING_PHASE
     */
    public void setPricingPhase(String value) {
        setAttributeInternal(PRICINGPHASE, value);
    }

    /**
     * Gets the attribute value for BUCKET using the alias name Bucket.
     * @return the BUCKET
     */
    public String getBucket() {
        return (String) getAttributeInternal(BUCKET);
    }

    /**
     * Sets <code>value</code> as attribute value for BUCKET using the alias name Bucket.
     * @param value value to set the BUCKET
     */
    public void setBucket(String value) {
        setAttributeInternal(BUCKET, value);
    }

    /**
     * Gets the attribute value for PRODUCT_ATTRIBUTE_CODE using the alias name ProductAttributeCode.
     * @return the PRODUCT_ATTRIBUTE_CODE
     */
    public String getProductAttributeCode() {
        return (String) getAttributeInternal(PRODUCTATTRIBUTECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCT_ATTRIBUTE_CODE using the alias name ProductAttributeCode.
     * @param value value to set the PRODUCT_ATTRIBUTE_CODE
     */
    public void setProductAttributeCode(String value) {
        setAttributeInternal(PRODUCTATTRIBUTECODE, value);
    }

    /**
     * Gets the attribute value for PRODUCT_ATTRIBUTE using the alias name ProductAttribute.
     * @return the PRODUCT_ATTRIBUTE
     */
    public String getProductAttribute() {
        return (String) getAttributeInternal(PRODUCTATTRIBUTE);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCT_ATTRIBUTE using the alias name ProductAttribute.
     * @param value value to set the PRODUCT_ATTRIBUTE
     */
    public void setProductAttribute(String value) {
        setAttributeInternal(PRODUCTATTRIBUTE, value);
    }

    /**
     * Gets the attribute value for PRODUCT_ATTRIBUTE_VALUE_ID using the alias name ProductAttributeValueId.
     * @return the PRODUCT_ATTRIBUTE_VALUE_ID
     */
    public Number getProductAttributeValueId() {
        return (Number) getAttributeInternal(PRODUCTATTRIBUTEVALUEID);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCT_ATTRIBUTE_VALUE_ID using the alias name ProductAttributeValueId.
     * @param value value to set the PRODUCT_ATTRIBUTE_VALUE_ID
     */
    public void setProductAttributeValueId(Number value) {
        setAttributeInternal(PRODUCTATTRIBUTEVALUEID, value);
    }

    /**
     * Gets the attribute value for PRODUCT_ATTRIBUTE_VALUE using the alias name ProductAttributeValue.
     * @return the PRODUCT_ATTRIBUTE_VALUE
     */
    public String getProductAttributeValue() {
        return (String) getAttributeInternal(PRODUCTATTRIBUTEVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCT_ATTRIBUTE_VALUE using the alias name ProductAttributeValue.
     * @param value value to set the PRODUCT_ATTRIBUTE_VALUE
     */
    public void setProductAttributeValue(String value) {
        setAttributeInternal(PRODUCTATTRIBUTEVALUE, value);
    }

    /**
     * Gets the attribute value for PRODUCT_PRECEDENCE using the alias name ProductPrecedence.
     * @return the PRODUCT_PRECEDENCE
     */
    public Number getProductPrecedence() {
        return (Number) getAttributeInternal(PRODUCTPRECEDENCE);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCT_PRECEDENCE using the alias name ProductPrecedence.
     * @param value value to set the PRODUCT_PRECEDENCE
     */
    public void setProductPrecedence(Number value) {
        setAttributeInternal(PRODUCTPRECEDENCE, value);
    }

    /**
     * Gets the attribute value for VOLUME_TYPE using the alias name VolumeType.
     * @return the VOLUME_TYPE
     */
    public String getVolumeType() {
        return (String) getAttributeInternal(VOLUMETYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for VOLUME_TYPE using the alias name VolumeType.
     * @param value value to set the VOLUME_TYPE
     */
    public void setVolumeType(String value) {
        setAttributeInternal(VOLUMETYPE, value);
    }

    /**
     * Gets the attribute value for BREAK_TYPE using the alias name BreakType.
     * @return the BREAK_TYPE
     */
    public String getBreakType() {
        return (String) getAttributeInternal(BREAKTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for BREAK_TYPE using the alias name BreakType.
     * @param value value to set the BREAK_TYPE
     */
    public void setBreakType(String value) {
        setAttributeInternal(BREAKTYPE, value);
    }

    /**
     * Gets the attribute value for UOM using the alias name Uom.
     * @return the UOM
     */
    public String getUom() {
        return (String) getAttributeInternal(UOM);
    }

    /**
     * Sets <code>value</code> as attribute value for UOM using the alias name Uom.
     * @param value value to set the UOM
     */
    public void setUom(String value) {
        setAttributeInternal(UOM, value);
    }

    /**
     * Gets the attribute value for VALUE_FROM using the alias name ValueFrom.
     * @return the VALUE_FROM
     */
    public String getValueFrom() {
        return (String) getAttributeInternal(VALUEFROM);
    }

    /**
     * Sets <code>value</code> as attribute value for VALUE_FROM using the alias name ValueFrom.
     * @param value value to set the VALUE_FROM
     */
    public void setValueFrom(String value) {
        setAttributeInternal(VALUEFROM, value);
    }

    /**
     * Gets the attribute value for VALUE_TO using the alias name ValueTo.
     * @return the VALUE_TO
     */
    public String getValueTo() {
        return (String) getAttributeInternal(VALUETO);
    }

    /**
     * Sets <code>value</code> as attribute value for VALUE_TO using the alias name ValueTo.
     * @param value value to set the VALUE_TO
     */
    public void setValueTo(String value) {
        setAttributeInternal(VALUETO, value);
    }

    /**
     * Gets the attribute value for APPLICATION_METHOD using the alias name ApplicationMethod.
     * @return the APPLICATION_METHOD
     */
    public String getApplicationMethod() {
        return (String) getAttributeInternal(APPLICATIONMETHOD);
    }

    /**
     * Sets <code>value</code> as attribute value for APPLICATION_METHOD using the alias name ApplicationMethod.
     * @param value value to set the APPLICATION_METHOD
     */
    public void setApplicationMethod(String value) {
        setAttributeInternal(APPLICATIONMETHOD, value);
    }

    /**
     * Gets the attribute value for VALUE using the alias name Value.
     * @return the VALUE
     */
    public Number getValue() {
        return (Number) getAttributeInternal(VALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for VALUE using the alias name Value.
     * @param value value to set the VALUE
     */
    public void setValue(Number value) {
        setAttributeInternal(VALUE, value);
    }

    /**
     * Gets the attribute value for GROUPING_NO using the alias name GroupingNo.
     * @return the GROUPING_NO
     */
    public Number getGroupingNo() {
        return (Number) getAttributeInternal(GROUPINGNO);
    }

    /**
     * Sets <code>value</code> as attribute value for GROUPING_NO using the alias name GroupingNo.
     * @param value value to set the GROUPING_NO
     */
    public void setGroupingNo(Number value) {
        setAttributeInternal(GROUPINGNO, value);
    }

    /**
     * Gets the attribute value for QUALIFIER_CONTEXT using the alias name QualifierContext.
     * @return the QUALIFIER_CONTEXT
     */
    public String getQualifierContext() {
        return (String) getAttributeInternal(QUALIFIERCONTEXT);
    }

    /**
     * Sets <code>value</code> as attribute value for QUALIFIER_CONTEXT using the alias name QualifierContext.
     * @param value value to set the QUALIFIER_CONTEXT
     */
    public void setQualifierContext(String value) {
        setAttributeInternal(QUALIFIERCONTEXT, value);
    }

    /**
     * Gets the attribute value for QUALIFIER_ATTR using the alias name QualifierAttr.
     * @return the QUALIFIER_ATTR
     */
    public String getQualifierAttr() {
        return (String) getAttributeInternal(QUALIFIERATTR);
    }

    /**
     * Sets <code>value</code> as attribute value for QUALIFIER_ATTR using the alias name QualifierAttr.
     * @param value value to set the QUALIFIER_ATTR
     */
    public void setQualifierAttr(String value) {
        setAttributeInternal(QUALIFIERATTR, value);
    }

    /**
     * Gets the attribute value for QUALIFIER_ATTR_ID using the alias name QualifierAttrId.
     * @return the QUALIFIER_ATTR_ID
     */
    public String getQualifierAttrId() {
        return (String) getAttributeInternal(QUALIFIERATTRID);
    }

    /**
     * Sets <code>value</code> as attribute value for QUALIFIER_ATTR_ID using the alias name QualifierAttrId.
     * @param value value to set the QUALIFIER_ATTR_ID
     */
    public void setQualifierAttrId(String value) {
        setAttributeInternal(QUALIFIERATTRID, value);
    }

    /**
     * Gets the attribute value for QUALIFIER_PRECEDENCE using the alias name QualifierPrecedence.
     * @return the QUALIFIER_PRECEDENCE
     */
    public Number getQualifierPrecedence() {
        return (Number) getAttributeInternal(QUALIFIERPRECEDENCE);
    }

    /**
     * Sets <code>value</code> as attribute value for QUALIFIER_PRECEDENCE using the alias name QualifierPrecedence.
     * @param value value to set the QUALIFIER_PRECEDENCE
     */
    public void setQualifierPrecedence(Number value) {
        setAttributeInternal(QUALIFIERPRECEDENCE, value);
    }

    /**
     * Gets the attribute value for OPERATOR using the alias name Operator1.
     * @return the OPERATOR
     */
    public String getOperator1() {
        return (String) getAttributeInternal(OPERATOR1);
    }

    /**
     * Sets <code>value</code> as attribute value for OPERATOR using the alias name Operator1.
     * @param value value to set the OPERATOR
     */
    public void setOperator1(String value) {
        setAttributeInternal(OPERATOR1, value);
    }

    /**
     * Gets the attribute value for Q_VALUE_FROM using the alias name QValueFrom.
     * @return the Q_VALUE_FROM
     */
    public String getQValueFrom() {
        return (String) getAttributeInternal(QVALUEFROM);
    }

    /**
     * Sets <code>value</code> as attribute value for Q_VALUE_FROM using the alias name QValueFrom.
     * @param value value to set the Q_VALUE_FROM
     */
    public void setQValueFrom(String value) {
        setAttributeInternal(QVALUEFROM, value);
    }

    /**
     * Gets the attribute value for Q_VALUE_TO using the alias name QValueTo.
     * @return the Q_VALUE_TO
     */
    public String getQValueTo() {
        return (String) getAttributeInternal(QVALUETO);
    }

    /**
     * Sets <code>value</code> as attribute value for Q_VALUE_TO using the alias name QValueTo.
     * @param value value to set the Q_VALUE_TO
     */
    public void setQValueTo(String value) {
        setAttributeInternal(QVALUETO, value);
    }

    /**
     * Gets the attribute value for START_DATE_QUALIFIER using the alias name StartDateQualifier.
     * @return the START_DATE_QUALIFIER
     */
    public Date getStartDateQualifier() {
        return (Date) getAttributeInternal(STARTDATEQUALIFIER);
    }

    /**
     * Sets <code>value</code> as attribute value for START_DATE_QUALIFIER using the alias name StartDateQualifier.
     * @param value value to set the START_DATE_QUALIFIER
     */
    public void setStartDateQualifier(Date value) {
        setAttributeInternal(STARTDATEQUALIFIER, value);
    }

    /**
     * Gets the attribute value for END_DATE_QUALIFIER using the alias name EndDateQualifier.
     * @return the END_DATE_QUALIFIER
     */
    public Date getEndDateQualifier() {
        return (Date) getAttributeInternal(ENDDATEQUALIFIER);
    }

    /**
     * Sets <code>value</code> as attribute value for END_DATE_QUALIFIER using the alias name EndDateQualifier.
     * @param value value to set the END_DATE_QUALIFIER
     */
    public void setEndDateQualifier(Date value) {
        setAttributeInternal(ENDDATEQUALIFIER, value);
    }

    /**
     * Gets the attribute value for FLAG using the alias name Flag.
     * @return the FLAG
     */
    public String getFlag() {
        return (String) getAttributeInternal(FLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for FLAG using the alias name Flag.
     * @param value value to set the FLAG
     */
    public void setFlag(String value) {
        setAttributeInternal(FLAG, value);
    }

    /**
     * Gets the attribute value for MESSAGE using the alias name Message.
     * @return the MESSAGE
     */
    public String getMessage() {
        return (String) getAttributeInternal(MESSAGE);
    }

    /**
     * Sets <code>value</code> as attribute value for MESSAGE using the alias name Message.
     * @param value value to set the MESSAGE
     */
    public void setMessage(String value) {
        setAttributeInternal(MESSAGE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for UPDATED_DATE using the alias name UpdatedDate.
     * @return the UPDATED_DATE
     */
    public Date getUpdatedDate() {
        return (Date) getAttributeInternal(UPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for UPDATED_DATE using the alias name UpdatedDate.
     * @param value value to set the UPDATED_DATE
     */
    public void setUpdatedDate(Date value) {
        setAttributeInternal(UPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for ROWID using the alias name RowID.
     * @return the ROWID
     */
    public RowID getRowID() {
        return (RowID) getAttributeInternal(ROWID);
    }

    /**
     * Sets <code>value</code> as attribute value for ROWID using the alias name RowID.
     * @param value value to set the ROWID
     */
    public void setRowID(RowID value) {
        setAttributeInternal(ROWID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
