package app.fpp.model.views.confirmation.modifier;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 14 09:56:50 ICT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FcsQpModifierTempViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FcsQpModifierTempViewImpl() {
    }
}
