package app.fpp.model.am;

import app.fpp.adfextensions.CustomApplicationModuleImpl;
import app.fpp.model.am.common.ApprovalSettingAM;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 05 07:08:28 ICT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ApprovalSettingAMImpl extends CustomApplicationModuleImpl implements ApprovalSettingAM {
    /**
     * This is the default constructor (do not remove).
     */
    public ApprovalSettingAMImpl() {
    }
        
    public void setLoginToSession_ApprovalSettingAM(String key, String val) {
        this.setLoginToSession(key, val);
    }

    /**
     * Container's getter for ApprovalFlowView1.
     * @return ApprovalFlowView1
     */
    public ViewObjectImpl getApprovalFlowView1() {
        return (ViewObjectImpl)findViewObject("ApprovalFlowView1");
    }

    /**
     * Container's getter for ApprovalStepsView1.
     * @return ApprovalStepsView1
     */
    public ViewObjectImpl getApprovalStepsView1() {
        return (ViewObjectImpl)findViewObject("ApprovalStepsView1");
    }

    /**
     * Container's getter for ApprovalStepsApprovalFFk1Link1.
     * @return ApprovalStepsApprovalFFk1Link1
     */
    public ViewLinkImpl getApprovalStepsApprovalFFk1Link1() {
        return (ViewLinkImpl)findViewLink("ApprovalStepsApprovalFFk1Link1");
    }
}
