package app.fpp.model.am;

import app.fpp.adfextensions.CustomApplicationModuleImpl;

import app.fpp.model.am.common.DashboardAM;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 19 13:11:44 ICT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DashboardAMImpl extends CustomApplicationModuleImpl implements DashboardAM {
    /**
     * This is the default constructor (do not remove).
     */
    public DashboardAMImpl() {
    }
        
    public void setLoginToSession_DashboardAM(String key, String val) {
        this.setLoginToSession(key, val);
    }
    
    /**
     * Container's getter for ApprovalDashView1.
     * @return ApprovalDashView1
     */
    public ViewObjectImpl getApprovalDashView1() {
        return (ViewObjectImpl)findViewObject("ApprovalDashView1");
    }

    /**
     * Container's getter for ConfirmationDashView1.
     * @return ConfirmationDashView1
     */
    public ViewObjectImpl getConfirmationDashView1() {
        return (ViewObjectImpl)findViewObject("ConfirmationDashView1");
    }

    /**
     * Container's getter for ProposalDashView1.
     * @return ProposalDashView1
     */
    public ViewObjectImpl getProposalDashView1() {
        return (ViewObjectImpl)findViewObject("ProposalDashView1");
    }
}
