package app.fpp.model.am;

import app.fpp.adfextensions.CustomApplicationModuleImpl;
import app.fpp.model.am.common.PromoProposalAM;
import app.fpp.model.views.approval.ApprovalReceiverNewProposalViewImpl;
import app.fpp.model.views.masterdata.ebs.FcsViewCategCombinationViewImpl;
import app.fpp.model.views.promoproposal.FindRegionCodeImpl;
import app.fpp.model.views.promoproposal.PromoBonusVariantViewImpl;
import app.fpp.model.views.promoproposal.duplicate.DuplicateBiayaViewImpl;
import app.fpp.model.views.promoproposal.duplicate.DuplicateProdExclAreaViewImpl;
import app.fpp.model.views.promoproposal.duplicate.DuplicateProdExclCustomerViewImpl;
import app.fpp.model.views.promoproposal.duplicate.DuplicateProdExclLocViewImpl;
import app.fpp.model.views.promoproposal.duplicate.DuplicateProdExclRegionViewImpl;
import app.fpp.model.views.promoproposal.duplicate.DuplicateProdRegionAreaViewImpl;
import app.fpp.model.views.promoproposal.duplicate.DuplicateProdRegionCustGroupViewImpl;
import app.fpp.model.views.promoproposal.duplicate.DuplicateProdRegionCustomerViewImpl;
import app.fpp.model.views.promoproposal.duplicate.DuplicateProdRegionLocViewImpl;
import app.fpp.model.views.promoproposal.duplicate.DuplicateProdRegionViewImpl;
import app.fpp.model.views.promoproposal.duplicate.DuplicateProdukItemViewImpl;
import app.fpp.model.views.promoproposal.duplicate.DuplicateProdukVariantViewImpl;
import app.fpp.model.views.promoproposal.duplicate.DuplicatePromoBonusViewImpl;
import app.fpp.model.views.promoproposal.validation.ProdVariantValidationViewImpl;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import oracle.jbo.JboException;
import oracle.jbo.Row;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 12 10:29:15 ICT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PromoProposalAMImpl extends CustomApplicationModuleImpl implements PromoProposalAM {
    /**
     * This is the default constructor (do not remove).
     */
    private static final String initReason = "Initial proposal";
    private static final String resubmitReason = "Re-submited proposal";
    
    public PromoProposalAMImpl() {
    }

    public void setLoginToSession_PromoProposalAM(String key, String val) {
        this.setLoginToSession(key, val);
    }

    public void addDocApproval(String propId, String docNo, String docStatus,
                               String promoDtFrom, String promoDtTo,
                               String docRegion, String usrRole, String userNm,
                               String aprvlFlowNm, String propDt) {
        
        //Choose reason init or resubmit
        String reasonStr = initReason;
        ViewObjectImpl docApproval = this.getDocApprovalView1();
        docApproval.setWhereClause("DocApproval.PROPOSAL_ID=" + propId);
        docApproval.executeQuery();
        if (docApproval.getEstimatedRowCount() > 0) {
            reasonStr = resubmitReason;
        } else {
            reasonStr = initReason;
        }
        
        //Retrieve proposal receiver role
        ViewObjectImpl proposalReceiver =
            this.getApprovalReceiverNewProposalView1();
        proposalReceiver.setNamedWhereClauseParam("aprvlFlowNm", aprvlFlowNm);
        proposalReceiver.setNamedWhereClauseParam("usrName", userNm);
        proposalReceiver.executeQuery();

        if (proposalReceiver.getEstimatedRowCount() > 0) {
            Row propReceiverRow = proposalReceiver.first();
            String roleName = (String)propReceiverRow.getAttribute("RoleName");
            String userName = (String)propReceiverRow.getAttribute("UserName");
            String aprvlCode =
                (String)propReceiverRow.getAttribute("AprvlCode");

            PreparedStatement addDocApprovalStmt = null;
            PreparedStatement addDocInitApprovalStmt = null;

            try {

                String SQLInit =
                    "INSERT INTO DOC_APPROVAL (DOC_APPROVAL_ID, PROPOSAL_ID, DOCUMENT_NO, STATUS, PROMO_DATE_FROM, PROMO_DATE_TO, ACTION, ACTION_DATE, ACTION_BY, REASON, ROLE_NAME, REGION, APRVL_CODE, CREATED_BY, CREATION_DATE, ACTION_TO, PROPOSAL_DATE) " +
                    "VALUES (DOC_APPROVAL_SEQ.NEXTVAL, TO_NUMBER(" + propId +
                    "), '" + docNo + "', '" + docStatus +
                    "', TO_DATE(UPPER('" + promoDtFrom +
                    "'), 'DD-MON-YYYY'), " + "TO_DATE(UPPER('" + promoDtTo +
                    "'), 'DD-MON-YYYY'), 'SUBMIT', SYSDATE, '" + userNm +
                    "', '" + reasonStr + "', '" + usrRole + "', '" + docRegion + "', '" +
                    aprvlCode + "', '" + userNm + "', SYSDATE, '" + userNm + "', TO_DATE(UPPER('" + propDt + "'), 'DD-MON-YYYY hh:mi:ss'))";

                addDocInitApprovalStmt =
                        getDBTransaction().createPreparedStatement(SQLInit, 1);
                addDocInitApprovalStmt.executeUpdate();

                String SQL =
                    "INSERT INTO DOC_APPROVAL (DOC_APPROVAL_ID, PROPOSAL_ID, DOCUMENT_NO, STATUS, PROMO_DATE_FROM, PROMO_DATE_TO, ROLE_NAME, REGION, APRVL_CODE, CREATED_BY, CREATION_DATE, ACTION_TO, PROPOSAL_DATE) " +
                    "VALUES (DOC_APPROVAL_SEQ.NEXTVAL, TO_NUMBER(" + propId +
                    "), '" + docNo + "', '" + docStatus +
                    "', TO_DATE(UPPER('" + promoDtFrom +
                    "'), 'DD-MON-YYYY'), " + "TO_DATE(UPPER('" + promoDtTo +
                    "'), 'DD-MON-YYYY'), '" + roleName + "', '" + docRegion +
                    "', '" + aprvlCode + "', '" + userNm + "', SYSDATE, '" + userName + "', TO_DATE(UPPER('" + propDt + "'), 'DD-MON-YYYY hh:mi:ss'))";

                addDocApprovalStmt =
                        getDBTransaction().createPreparedStatement(SQL, 1);
                addDocApprovalStmt.executeUpdate();
            } catch (SQLException e) {
                throw new JboException(e.getMessage());
            } finally {
                getDBTransaction().commit();
                if (addDocApprovalStmt != null) {
                    try {
                        addDocApprovalStmt.close();
                    } catch (Exception e) {
                        throw new JboException(e.getMessage());
                    }
                }
            }
        } else {
            getDBTransaction().rollback();
            throw new JboException("User penerima pada flow approval tidak ditemukan.");
        }
    }

    /**
     * Container's getter for ProposalView1.
     * @return ProposalView1
     */
    public ViewObjectImpl getProposalView1() {
        return (ViewObjectImpl)findViewObject("ProposalView1");
    }

    /**
     * Container's getter for PromoProdukView1.
     * @return PromoProdukView1
     */
    public ViewObjectImpl getPromoProdukView1() {
        return (ViewObjectImpl)findViewObject("PromoProdukView1");
    }


    /**
     * Container's getter for DiscountView1.
     * @return DiscountView1
     */
    public ViewObjectImpl getDiscountView1() {
        return (ViewObjectImpl)findViewObject("DiscountView1");
    }

    /**
     * Container's getter for TargetView1.
     * @return TargetView1
     */
    public ViewObjectImpl getTargetView1() {
        return (ViewObjectImpl)findViewObject("TargetView1");
    }

    /**
     * Container's getter for PromoProdukProposalFk1Link1.
     * @return PromoProdukProposalFk1Link1
     */
    public ViewLinkImpl getPromoProdukProposalFk1Link1() {
        return (ViewLinkImpl)findViewLink("PromoProdukProposalFk1Link1");
    }


    /**
     * Container's getter for DiscountPromoProdukFk1Link1.
     * @return DiscountPromoProdukFk1Link1
     */
    public ViewLinkImpl getDiscountPromoProdukFk1Link1() {
        return (ViewLinkImpl)findViewLink("DiscountPromoProdukFk1Link1");
    }

    /**
     * Container's getter for TargetPromoProdukFk1Link1.
     * @return TargetPromoProdukFk1Link1
     */
    public ViewLinkImpl getTargetPromoProdukFk1Link1() {
        return (ViewLinkImpl)findViewLink("TargetPromoProdukFk1Link1");
    }

    /**
     * Container's getter for RunNumPropView1.
     * @return RunNumPropView1
     */
    public ViewObjectImpl getRunNumPropView1() {
        return (ViewObjectImpl)findViewObject("RunNumPropView1");
    }

    /**
     * Container's getter for DocApprovalView1.
     * @return DocApprovalView1
     */
    public ViewObjectImpl getDocApprovalView1() {
        return (ViewObjectImpl)findViewObject("DocApprovalView1");
    }

    /**
     * Container's getter for DocApprovalProposalFk1Link1.
     * @return DocApprovalProposalFk1Link1
     */
    public ViewLinkImpl getDocApprovalProposalFk1Link1() {
        return (ViewLinkImpl)findViewLink("DocApprovalProposalFk1Link1");
    }

    /**
     * Container's getter for ApprovalReceiverNewProposalView1.
     * @return ApprovalReceiverNewProposalView1
     */
    public ApprovalReceiverNewProposalViewImpl getApprovalReceiverNewProposalView1() {
        return (ApprovalReceiverNewProposalViewImpl)findViewObject("ApprovalReceiverNewProposalView1");
    }


    /**
     * Container's getter for ProposalGetUserInitialView1.
     * @return ProposalGetUserInitialView1
     */
    public ViewObjectImpl getProposalGetUserInitialView1() {
        return (ViewObjectImpl)findViewObject("ProposalGetUserInitialView1");
    }

    /**
     * Container's getter for PropRegionView1.
     * @return PropRegionView1
     */
    public ViewObjectImpl getPropRegionView1() {
        return (ViewObjectImpl)findViewObject("PropRegionView1");
    }

    /**
     * Container's getter for ProposalPropRegionFkLink1.
     * @return ProposalPropRegionFkLink1
     */
    public ViewLinkImpl getProposalPropRegionFkLink1() {
        return (ViewLinkImpl)findViewLink("ProposalPropRegionFkLink1");
    }

    /**
     * Container's getter for PropRegionCustomerView1.
     * @return PropRegionCustomerView1
     */
    public ViewObjectImpl getPropRegionCustomerView1() {
        return (ViewObjectImpl)findViewObject("PropRegionCustomerView1");
    }

    /**
     * Container's getter for ProposalPropRegionCustomerFkLink1.
     * @return ProposalPropRegionCustomerFkLink1
     */
    public ViewLinkImpl getProposalPropRegionCustomerFkLink1() {
        return (ViewLinkImpl)findViewLink("ProposalPropRegionCustomerFkLink1");
    }

    /**
     * Container's getter for AllProposalRegionShuttleView1.
     * @return AllProposalRegionShuttleView1
     */
    public ViewObjectImpl getAllProposalRegionShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllProposalRegionShuttleView1");
    }

    /**
     * Container's getter for AllProposalCustomerShuttleView1.
     * @return AllProposalCustomerShuttleView1
     */
    public ViewObjectImpl getAllProposalCustomerShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllProposalCustomerShuttleView1");
    }

    /**
     * Container's getter for ProdukItemView1.
     * @return ProdukItemView1
     */
    public ViewObjectImpl getProdukItemView1() {
        return (ViewObjectImpl)findViewObject("ProdukItemView1");
    }

    /**
     * Container's getter for ProdukItemPromoProdukFk1Link1.
     * @return ProdukItemPromoProdukFk1Link1
     */
    public ViewLinkImpl getProdukItemPromoProdukFk1Link1() {
        return (ViewLinkImpl)findViewLink("ProdukItemPromoProdukFk1Link1");
    }

    /**
     * Container's getter for ProdukVariantView1.
     * @return ProdukVariantView1
     */
    public ViewObjectImpl getProdukVariantView1() {
        return (ViewObjectImpl)findViewObject("ProdukVariantView1");
    }

    /**
     * Container's getter for ProdukVariantPromoProdukFk1Link1.
     * @return ProdukVariantPromoProdukFk1Link1
     */
    public ViewLinkImpl getProdukVariantPromoProdukFk1Link1() {
        return (ViewLinkImpl)findViewLink("ProdukVariantPromoProdukFk1Link1");
    }

    /**
     * Container's getter for AllProdukVariantShuttleView1.
     * @return AllProdukVariantShuttleView1
     */
    public ViewObjectImpl getAllProdukVariantShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllProdukVariantShuttleView1");
    }

    /**
     * Container's getter for AllProdukItemShuttleView1.
     * @return AllProdukItemShuttleView1
     */
    public ViewObjectImpl getAllProdukItemShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllProdukItemShuttleView1");
    }

    /**
     * Container's getter for BiayaView1.
     * @return BiayaView1
     */
    public ViewObjectImpl getBiayaView1() {
        return (ViewObjectImpl)findViewObject("BiayaView1");
    }

    /**
     * Container's getter for BiayaPromoProdukFk1Link1.
     * @return BiayaPromoProdukFk1Link1
     */
    public ViewLinkImpl getBiayaPromoProdukFk1Link1() {
        return (ViewLinkImpl)findViewLink("BiayaPromoProdukFk1Link1");
    }


    /**
     * Container's getter for PromoBonusView1.
     * @return PromoBonusView1
     */
    public ViewObjectImpl getPromoBonusView1() {
        return (ViewObjectImpl)findViewObject("PromoBonusView1");
    }

    /**
     * Container's getter for PromoBonusPromoProdukFk1Link1.
     * @return PromoBonusPromoProdukFk1Link1
     */
    public ViewLinkImpl getPromoBonusPromoProdukFk1Link1() {
        return (ViewLinkImpl)findViewLink("PromoBonusPromoProdukFk1Link1");
    }


    /**
     * Container's getter for PromoBonusProdItemView1.
     * @return PromoBonusProdItemView1
     */
    public ViewObjectImpl getPromoBonusProdItemView1() {
        return (ViewObjectImpl)findViewObject("PromoBonusProdItemView1");
    }

    /**
     * Container's getter for PromoBonusProdItemPromoBonusFk1Link1.
     * @return PromoBonusProdItemPromoBonusFk1Link1
     */
    public ViewLinkImpl getPromoBonusProdItemPromoBonusFk1Link1() {
        return (ViewLinkImpl)findViewLink("PromoBonusProdItemPromoBonusFk1Link1");
    }


    /**
     * Container's getter for ProdRegionView1.
     * @return ProdRegionView1
     */
    public ViewObjectImpl getProdRegionView1() {
        return (ViewObjectImpl)findViewObject("ProdRegionView1");
    }

    /**
     * Container's getter for ProdRegionPromoProdukFk1Link1.
     * @return ProdRegionPromoProdukFk1Link1
     */
    public ViewLinkImpl getProdRegionPromoProdukFk1Link1() {
        return (ViewLinkImpl)findViewLink("ProdRegionPromoProdukFk1Link1");
    }

    /**
     * Container's getter for ProdRegionCustomerView1.
     * @return ProdRegionCustomerView1
     */
    public ViewObjectImpl getProdRegionCustomerView1() {
        return (ViewObjectImpl)findViewObject("ProdRegionCustomerView1");
    }

    /**
     * Container's getter for ProdRegionCustomerPromoProdukFk1Link1.
     * @return ProdRegionCustomerPromoProdukFk1Link1
     */
    public ViewLinkImpl getProdRegionCustomerPromoProdukFk1Link1() {
        return (ViewLinkImpl)findViewLink("ProdRegionCustomerPromoProdukFk1Link1");
    }


    /**
     * Container's getter for ProdRegionAreaView1.
     * @return ProdRegionAreaView1
     */
    public ViewObjectImpl getProdRegionAreaView1() {
        return (ViewObjectImpl)findViewObject("ProdRegionAreaView1");
    }

    /**
     * Container's getter for ProdRegionAreaPromoProdukFk1Link1.
     * @return ProdRegionAreaPromoProdukFk1Link1
     */
    public ViewLinkImpl getProdRegionAreaPromoProdukFk1Link1() {
        return (ViewLinkImpl)findViewLink("ProdRegionAreaPromoProdukFk1Link1");
    }

    /**
     * Container's getter for AllProdukRegionShuttleView1.
     * @return AllProdukRegionShuttleView1
     */
    public ViewObjectImpl getAllProdukRegionShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllProdukRegionShuttleView1");
    }

    /**
     * Container's getter for AllProdukCustomerShuttleView1.
     * @return AllProdukCustomerShuttleView1
     */
    public ViewObjectImpl getAllProdukCustomerShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllProdukCustomerShuttleView1");
    }

    /**
     * Container's getter for AllProdukAreaShuttleView1.
     * @return AllProdukAreaShuttleView1
     */
    public ViewObjectImpl getAllProdukAreaShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllProdukAreaShuttleView1");
    }

    /**
     * Container's getter for DuplicateProdukVariantView1.
     * @return DuplicateProdukVariantView1
     */
    public DuplicateProdukVariantViewImpl getDuplicateProdukVariantView1() {
        return (DuplicateProdukVariantViewImpl)findViewObject("DuplicateProdukVariantView1");
    }

    /**
     * Container's getter for DuplicateProdukItemView1.
     * @return DuplicateProdukItemView1
     */
    public DuplicateProdukItemViewImpl getDuplicateProdukItemView1() {
        return (DuplicateProdukItemViewImpl)findViewObject("DuplicateProdukItemView1");
    }

    /**
     * Container's getter for DuplicateTargetView1.
     * @return DuplicateTargetView1
     */
    public ViewObjectImpl getDuplicateTargetView1() {
        return (ViewObjectImpl)findViewObject("DuplicateTargetView1");
    }

    /**
     * Container's getter for DuplicateDiscountView1.
     * @return DuplicateDiscountView1
     */
    public ViewObjectImpl getDuplicateDiscountView1() {
        return (ViewObjectImpl)findViewObject("DuplicateDiscountView1");
    }

    /**
     * Container's getter for DuplicateBiayaView1.
     * @return DuplicateBiayaView1
     */
    public DuplicateBiayaViewImpl getDuplicateBiayaView1() {
        return (DuplicateBiayaViewImpl)findViewObject("DuplicateBiayaView1");
    }


    /**
     * Container's getter for DuplicatePromoBonusView1.
     * @return DuplicatePromoBonusView1
     */
    public DuplicatePromoBonusViewImpl getDuplicatePromoBonusView1() {
        return (DuplicatePromoBonusViewImpl)findViewObject("DuplicatePromoBonusView1");
    }

    /**
     * Container's getter for DuplicateProdRegionAreaView1.
     * @return DuplicateProdRegionAreaView1
     */
    public DuplicateProdRegionAreaViewImpl getDuplicateProdRegionAreaView1() {
        return (DuplicateProdRegionAreaViewImpl)findViewObject("DuplicateProdRegionAreaView1");
    }

    /**
     * Container's getter for DuplicateProdRegionCustomerView1.
     * @return DuplicateProdRegionCustomerView1
     */
    public DuplicateProdRegionCustomerViewImpl getDuplicateProdRegionCustomerView1() {
        return (DuplicateProdRegionCustomerViewImpl)findViewObject("DuplicateProdRegionCustomerView1");
    }

    /**
     * Container's getter for DuplicateProdRegionView1.
     * @return DuplicateProdRegionView1
     */
    public DuplicateProdRegionViewImpl getDuplicateProdRegionView1() {
        return (DuplicateProdRegionViewImpl)findViewObject("DuplicateProdRegionView1");
    }


    /**
     * Container's getter for PromoBonusVariantView1.
     * @return PromoBonusVariantView1
     */
    public PromoBonusVariantViewImpl getPromoBonusVariantView1() {
        return (PromoBonusVariantViewImpl)findViewObject("PromoBonusVariantView1");
    }

    /**
     * Container's getter for PromoBonusVariantPromoBonusFk1Link1.
     * @return PromoBonusVariantPromoBonusFk1Link1
     */
    public ViewLinkImpl getPromoBonusVariantPromoBonusFk1Link1() {
        return (ViewLinkImpl)findViewLink("PromoBonusVariantPromoBonusFk1Link1");
    }

    /**
     * Container's getter for ProdVariantValidationView1.
     * @return ProdVariantValidationView1
     */
    public ProdVariantValidationViewImpl getProdVariantValidationView1() {
        return (ProdVariantValidationViewImpl)findViewObject("ProdVariantValidationView1");
    }

    /**
     * Container's getter for FcsViewCategCombinationView1.
     * @return FcsViewCategCombinationView1
     */
    public FcsViewCategCombinationViewImpl getFcsViewCategCombinationView1() {
        return (FcsViewCategCombinationViewImpl)findViewObject("FcsViewCategCombinationView1");
    }

    /**
     * Container's getter for ProdRegionLocView1.
     * @return ProdRegionLocView1
     */
    public ViewObjectImpl getProdRegionLocView1() {
        return (ViewObjectImpl)findViewObject("ProdRegionLocView1");
    }

    /**
     * Container's getter for ProdRegionLocPromoProdukFk1Link1.
     * @return ProdRegionLocPromoProdukFk1Link1
     */
    public ViewLinkImpl getProdRegionLocPromoProdukFk1Link1() {
        return (ViewLinkImpl)findViewLink("ProdRegionLocPromoProdukFk1Link1");
    }

    /**
     * Container's getter for PropRegionLocView1.
     * @return PropRegionLocView1
     */
    public ViewObjectImpl getPropRegionLocView1() {
        return (ViewObjectImpl)findViewObject("PropRegionLocView1");
    }

    /**
     * Container's getter for ProposalPropRegionLocFk1Link1.
     * @return ProposalPropRegionLocFk1Link1
     */
    public ViewLinkImpl getProposalPropRegionLocFk1Link1() {
        return (ViewLinkImpl)findViewLink("ProposalPropRegionLocFk1Link1");
    }

    /**
     * Container's getter for PropRegionAreaView1.
     * @return PropRegionAreaView1
     */
    public ViewObjectImpl getPropRegionAreaView1() {
        return (ViewObjectImpl)findViewObject("PropRegionAreaView1");
    }

    /**
     * Container's getter for ProposalPropRegionAreaFk1Link1.
     * @return ProposalPropRegionAreaFk1Link1
     */
    public ViewLinkImpl getProposalPropRegionAreaFk1Link1() {
        return (ViewLinkImpl)findViewLink("ProposalPropRegionAreaFk1Link1");
    }

    /**
     * Container's getter for AllProdukLocationShuttleView1.
     * @return AllProdukLocationShuttleView1
     */
    public ViewObjectImpl getAllProdukLocationShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllProdukLocationShuttleView1");
    }

    /**
     * Container's getter for AllProposalAreaShuttleView1.
     * @return AllProposalAreaShuttleView1
     */
    public ViewObjectImpl getAllProposalAreaShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllProposalAreaShuttleView1");
    }

    /**
     * Container's getter for AllProposalLocationShuttleView1.
     * @return AllProposalLocationShuttleView1
     */
    public ViewObjectImpl getAllProposalLocationShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllProposalLocationShuttleView1");
    }

    /**
     * Container's getter for ApprovalRegPropView1.
     * @return ApprovalRegPropView1
     */
    public ViewObjectImpl getApprovalRegPropView1() {
        return (ViewObjectImpl)findViewObject("ApprovalRegPropView1");
    }

    /**
     * Container's getter for ApprovalRegPropProposalFk1Link1.
     * @return ApprovalRegPropProposalFk1Link1
     */
    public ViewLinkImpl getApprovalRegPropProposalFk1Link1() {
        return (ViewLinkImpl)findViewLink("ApprovalRegPropProposalFk1Link1");
    }

    /**
     * Container's getter for DuplicateProdRegionLocView1.
     * @return DuplicateProdRegionLocView1
     */
    public DuplicateProdRegionLocViewImpl getDuplicateProdRegionLocView1() {
        return (DuplicateProdRegionLocViewImpl)findViewObject("DuplicateProdRegionLocView1");
    }

    /**
     * Container's getter for ProdRegionCustGroupView1.
     * @return ProdRegionCustGroupView1
     */
    public ViewObjectImpl getProdRegionCustGroupView1() {
        return (ViewObjectImpl)findViewObject("ProdRegionCustGroupView1");
    }

    /**
     * Container's getter for ProdRegionCustGroupPromoProdukFk1Link1.
     * @return ProdRegionCustGroupPromoProdukFk1Link1
     */
    public ViewLinkImpl getProdRegionCustGroupPromoProdukFk1Link1() {
        return (ViewLinkImpl)findViewLink("ProdRegionCustGroupPromoProdukFk1Link1");
    }

    /**
     * Container's getter for PropRegionCustGroupView1.
     * @return PropRegionCustGroupView1
     */
    public ViewObjectImpl getPropRegionCustGroupView1() {
        return (ViewObjectImpl)findViewObject("PropRegionCustGroupView1");
    }

    /**
     * Container's getter for ProposalPropRegionCustGroupFk1Link1.
     * @return ProposalPropRegionCustGroupFk1Link1
     */
    public ViewLinkImpl getProposalPropRegionCustGroupFk1Link1() {
        return (ViewLinkImpl)findViewLink("ProposalPropRegionCustGroupFk1Link1");
    }

    /**
     * Container's getter for AllProdukCustGroupShuttleView1.
     * @return AllProdukCustGroupShuttleView1
     */
    public ViewObjectImpl getAllProdukCustGroupShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllProdukCustGroupShuttleView1");
    }

    /**
     * Container's getter for AllProposalCustGroupShuttleView1.
     * @return AllProposalCustGroupShuttleView1
     */
    public ViewObjectImpl getAllProposalCustGroupShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllProposalCustGroupShuttleView1");
    }

    /**
     * Container's getter for DuplicateProdRegionCustGroupView1.
     * @return DuplicateProdRegionCustGroupView1
     */
    public DuplicateProdRegionCustGroupViewImpl getDuplicateProdRegionCustGroupView1() {
        return (DuplicateProdRegionCustGroupViewImpl)findViewObject("DuplicateProdRegionCustGroupView1");
    }

    /**
     * Container's getter for LookupCodeView1.
     * @return LookupCodeView1
     */
    public ViewObjectImpl getLookupCodeView1() {
        return (ViewObjectImpl)findViewObject("LookupCodeView1");
    }

    /**
     * Container's getter for lovDivisiType1.
     * @return lovDivisiType1
     */
    public ViewObjectImpl getlovDivisiType1() {
        return (ViewObjectImpl)findViewObject("lovDivisiType1");
    }
    
    /**
     * Container's getter for FcsPppcPriceListView1.
     * @return FcsPppcPriceListView1
     */
    public ViewObjectImpl getFcsPppcPriceListView1() {
        return (ViewObjectImpl)findViewObject("FcsPppcPriceListView1");
    }

    /**
     * Container's getter for ExclCustAreaView1.
     * @return ExclCustAreaView1
     */
    public ViewObjectImpl getExclCustAreaView1() {
        return (ViewObjectImpl)findViewObject("ExclCustAreaView1");
    }

    /**
     * Container's getter for ExclCustAreaPromoProdukFk1Link1.
     * @return ExclCustAreaPromoProdukFk1Link1
     */
    public ViewLinkImpl getExclCustAreaPromoProdukFk1Link1() {
        return (ViewLinkImpl)findViewLink("ExclCustAreaPromoProdukFk1Link1");
    }

    /**
     * Container's getter for ExclCustLocView1.
     * @return ExclCustLocView1
     */
    public ViewObjectImpl getExclCustLocView1() {
        return (ViewObjectImpl)findViewObject("ExclCustLocView1");
    }

    /**
     * Container's getter for ExclCustLocPromoProdukFk1Link1.
     * @return ExclCustLocPromoProdukFk1Link1
     */
    public ViewLinkImpl getExclCustLocPromoProdukFk1Link1() {
        return (ViewLinkImpl)findViewLink("ExclCustLocPromoProdukFk1Link1");
    }

    /**
     * Container's getter for ExclCustRegionView1.
     * @return ExclCustRegionView1
     */
    public ViewObjectImpl getExclCustRegionView1() {
        return (ViewObjectImpl)findViewObject("ExclCustRegionView1");
    }

    /**
     * Container's getter for ExclCustRegionPromoProdukFk1Link1.
     * @return ExclCustRegionPromoProdukFk1Link1
     */
    public ViewLinkImpl getExclCustRegionPromoProdukFk1Link1() {
        return (ViewLinkImpl)findViewLink("ExclCustRegionPromoProdukFk1Link1");
    }


    /**
     * Container's getter for ExclCustCustView1.
     * @return ExclCustCustView1
     */
    public ViewObjectImpl getExclCustCustView1() {
        return (ViewObjectImpl)findViewObject("ExclCustCustView1");
    }

    /**
     * Container's getter for ExclCustCustPromoProdukFk1Link1.
     * @return ExclCustCustPromoProdukFk1Link1
     */
    public ViewLinkImpl getExclCustCustPromoProdukFk1Link1() {
        return (ViewLinkImpl)findViewLink("ExclCustCustPromoProdukFk1Link1");
    }


    /**
     * Container's getter for AllExclProposalAreaShuttleView1.
     * @return AllExclProposalAreaShuttleView1
     */
    public ViewObjectImpl getAllExclProposalAreaShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllExclProposalAreaShuttleView1");
    }

    /**
     * Container's getter for AllExclProposalCustomerShuttleView1.
     * @return AllExclProposalCustomerShuttleView1
     */
    public ViewObjectImpl getAllExclProposalCustomerShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllExclProposalCustomerShuttleView1");
    }

    /**
     * Container's getter for AllExclProposalLocationShuttleView1.
     * @return AllExclProposalLocationShuttleView1
     */
    public ViewObjectImpl getAllExclProposalLocationShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllExclProposalLocationShuttleView1");
    }

    /**
     * Container's getter for AllExclProposalRegionShuttleView1.
     * @return AllExclProposalRegionShuttleView1
     */
    public ViewObjectImpl getAllExclProposalRegionShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllExclProposalRegionShuttleView1");
    }

    /**
     * Container's getter for AllExcludeProdAreaShuttleView1.
     * @return AllExcludeProdAreaShuttleView1
     */
    public ViewObjectImpl getAllExcludeProdAreaShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllExcludeProdAreaShuttleView1");
    }

    /**
     * Container's getter for AllExcludeProdCustomerShuttleView1.
     * @return AllExcludeProdCustomerShuttleView1
     */
    public ViewObjectImpl getAllExcludeProdCustomerShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllExcludeProdCustomerShuttleView1");
    }

    /**
     * Container's getter for AllExcludeProdLocationShuttleView1.
     * @return AllExcludeProdLocationShuttleView1
     */
    public ViewObjectImpl getAllExcludeProdLocationShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllExcludeProdLocationShuttleView1");
    }

    /**
     * Container's getter for AllExcludeProdRegionShuttleView1.
     * @return AllExcludeProdRegionShuttleView1
     */
    public ViewObjectImpl getAllExcludeProdRegionShuttleView1() {
        return (ViewObjectImpl)findViewObject("AllExcludeProdRegionShuttleView1");
    }

    /**
     * Container's getter for DuplicateProdExclAreaView1.
     * @return DuplicateProdExclAreaView1
     */
    public DuplicateProdExclAreaViewImpl getDuplicateProdExclAreaView1() {
        return (DuplicateProdExclAreaViewImpl)findViewObject("DuplicateProdExclAreaView1");
    }

    /**
     * Container's getter for DuplicateProdExclCustomerView1.
     * @return DuplicateProdExclCustomerView1
     */
    public DuplicateProdExclCustomerViewImpl getDuplicateProdExclCustomerView1() {
        return (DuplicateProdExclCustomerViewImpl)findViewObject("DuplicateProdExclCustomerView1");
    }

    /**
     * Container's getter for DuplicateProdExclLocView1.
     * @return DuplicateProdExclLocView1
     */
    public DuplicateProdExclLocViewImpl getDuplicateProdExclLocView1() {
        return (DuplicateProdExclLocViewImpl)findViewObject("DuplicateProdExclLocView1");
    }

    /**
     * Container's getter for DuplicateProdExclRegionView1.
     * @return DuplicateProdExclRegionView1
     */
    public DuplicateProdExclRegionViewImpl getDuplicateProdExclRegionView1() {
        return (DuplicateProdExclRegionViewImpl)findViewObject("DuplicateProdExclRegionView1");
    }

    /**
     * Container's getter for ExclPropCustAreaView1.
     * @return ExclPropCustAreaView1
     */
    public ViewObjectImpl getExclPropCustAreaView1() {
        return (ViewObjectImpl)findViewObject("ExclPropCustAreaView1");
    }

    /**
     * Container's getter for ExclPropCustAreaPromoProdukFk1Link1.
     * @return ExclPropCustAreaPromoProdukFk1Link1
     */
    public ViewLinkImpl getExclPropCustAreaPromoProdukFk1Link1() {
        return (ViewLinkImpl)findViewLink("ExclPropCustAreaPromoProdukFk1Link1");
    }

    /**
     * Container's getter for ExclPropCustCustView1.
     * @return ExclPropCustCustView1
     */
    public ViewObjectImpl getExclPropCustCustView1() {
        return (ViewObjectImpl)findViewObject("ExclPropCustCustView1");
    }

    /**
     * Container's getter for ExclPropCustCustPromoProdukFk1Link1.
     * @return ExclPropCustCustPromoProdukFk1Link1
     */
    public ViewLinkImpl getExclPropCustCustPromoProdukFk1Link1() {
        return (ViewLinkImpl)findViewLink("ExclPropCustCustPromoProdukFk1Link1");
    }

    /**
     * Container's getter for ExclPropCustLocView1.
     * @return ExclPropCustLocView1
     */
    public ViewObjectImpl getExclPropCustLocView1() {
        return (ViewObjectImpl)findViewObject("ExclPropCustLocView1");
    }

    /**
     * Container's getter for ExclPropCustLocPromoProdukFk1Link1.
     * @return ExclPropCustLocPromoProdukFk1Link1
     */
    public ViewLinkImpl getExclPropCustLocPromoProdukFk1Link1() {
        return (ViewLinkImpl)findViewLink("ExclPropCustLocPromoProdukFk1Link1");
    }

    /**
     * Container's getter for ExclPropCustRegionView1.
     * @return ExclPropCustRegionView1
     */
    public ViewObjectImpl getExclPropCustRegionView1() {
        return (ViewObjectImpl)findViewObject("ExclPropCustRegionView1");
    }

    /**
     * Container's getter for ExclPropCustRegionPromoProdukFk1Link1.
     * @return ExclPropCustRegionPromoProdukFk1Link1
     */
    public ViewLinkImpl getExclPropCustRegionPromoProdukFk1Link1() {
        return (ViewLinkImpl)findViewLink("ExclPropCustRegionPromoProdukFk1Link1");
    }


    /**
     * Container's getter for UploadDownloadView1.
     * @return UploadDownloadView1
     */
    public ViewObjectImpl getUploadDownloadView1() {
        return (ViewObjectImpl)findViewObject("UploadDownloadView1");
    }

    /**
     * Container's getter for UploadDownloadProposalFk1Link1.
     * @return UploadDownloadProposalFk1Link1
     */
    public ViewLinkImpl getUploadDownloadProposalFk1Link1() {
        return (ViewLinkImpl)findViewLink("UploadDownloadProposalFk1Link1");
    }

    /**
     * Container's getter for FindRegionCode1.
     * @return FindRegionCode1
     */
    public FindRegionCodeImpl getFindRegionCode1() {
        return (FindRegionCodeImpl)findViewObject("FindRegionCode1");
    }
}
