package app.fpp.model.views.masterdata.ebs;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 04 11:46:20 ICT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AllKodePostingViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AllKodePostingViewImpl() {
    }

    /**
     * Returns the variable value for kdPosting.
     * @return variable value for kdPosting
     */
    public String getkdPosting() {
        return (String)ensureVariableManager().getVariableValue("kdPosting");
    }

    /**
     * Sets <code>value</code> for variable kdPosting.
     * @param value value to bind as kdPosting
     */
    public void setkdPosting(String value) {
        ensureVariableManager().setVariableValue("kdPosting", value);
    }
}
