package app.fpp.model.views.masterdata.ebs;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 20 13:53:10 ICT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FcsViewCategCombinationViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FcsViewCategCombinationViewImpl() {
    }

    /**
     * Returns the bind variable value for combVal.
     * @return bind variable value for combVal
     */
    public String getcombVal() {
        return (String)getNamedWhereClauseParam("combVal");
    }

    /**
     * Sets <code>value</code> for bind variable combVal.
     * @param value value to bind as combVal
     */
    public void setcombVal(String value) {
        setNamedWhereClauseParam("combVal", value);
    }
}
