package app.fpp.model.views.masterdata.ebs;

import oracle.jbo.domain.RowID;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 20 13:53:10 ICT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FcsViewCategCombinationViewRowImpl extends ViewRowImpl {

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ConcatenateCombination,
        PricingAttribute,
        SegmentCode;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int CONCATENATECOMBINATION = AttributesEnum.ConcatenateCombination.index();
    public static final int PRICINGATTRIBUTE = AttributesEnum.PricingAttribute.index();
    public static final int SEGMENTCODE = AttributesEnum.SegmentCode.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FcsViewCategCombinationViewRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute ConcatenateCombination.
     * @return the ConcatenateCombination
     */
    public String getConcatenateCombination() {
        return (String) getAttributeInternal(CONCATENATECOMBINATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ConcatenateCombination.
     * @param value value to set the  ConcatenateCombination
     */
    public void setConcatenateCombination(String value) {
        setAttributeInternal(CONCATENATECOMBINATION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PricingAttribute.
     * @return the PricingAttribute
     */
    public String getPricingAttribute() {
        return (String) getAttributeInternal(PRICINGATTRIBUTE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PricingAttribute.
     * @param value value to set the  PricingAttribute
     */
    public void setPricingAttribute(String value) {
        setAttributeInternal(PRICINGATTRIBUTE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SegmentCode.
     * @return the SegmentCode
     */
    public String getSegmentCode() {
        return (String) getAttributeInternal(SEGMENTCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SegmentCode.
     * @param value value to set the  SegmentCode
     */
    public void setSegmentCode(String value) {
        setAttributeInternal(SEGMENTCODE, value);
    }


}
