package app.fpp.model.views.masterdata.ebs;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 04 13:24:36 ICT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class KodePostingViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public KodePostingViewImpl() {
    }

    /**
     * Returns the bind variable value for kodePosting.
     * @return bind variable value for kodePosting
     */
    public String getkodePosting() {
        return (String)getNamedWhereClauseParam("kodePosting");
    }

    /**
     * Sets <code>value</code> for bind variable kodePosting.
     * @param value value to bind as kodePosting
     */
    public void setkodePosting(String value) {
        setNamedWhereClauseParam("kodePosting", value);
    }
}
