package app.fpp.model.views.budgetsetting;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 07 15:35:27 ICT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BudgetCustHdrViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public BudgetCustHdrViewImpl() {
    }
}
