package app.fpp.model.views.budgetsetting;

import app.fpp.model.entities.budgetsetting.BudgetCustTranImpl;

import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Dec 22 18:22:06 ICT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BudgetCustTranGetDataRowImpl extends ViewRowImpl {


    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Amount {
            public Object get(BudgetCustTranGetDataRowImpl obj) {
                return obj.getAmount();
            }

            public void put(BudgetCustTranGetDataRowImpl obj, Object value) {
                obj.setAmount((Number)value);
            }
        }
        ,
        BudgetAsToDate {
            public Object get(BudgetCustTranGetDataRowImpl obj) {
                return obj.getBudgetAsToDate();
            }

            public void put(BudgetCustTranGetDataRowImpl obj, Object value) {
                obj.setBudgetAsToDate((Number)value);
            }
        }
        ,
        BudgetCustTranId {
            public Object get(BudgetCustTranGetDataRowImpl obj) {
                return obj.getBudgetCustTranId();
            }

            public void put(BudgetCustTranGetDataRowImpl obj, Object value) {
                obj.setBudgetCustTranId((DBSequence)value);
            }
        }
        ,
        BudgetCustomerId {
            public Object get(BudgetCustTranGetDataRowImpl obj) {
                return obj.getBudgetCustomerId();
            }

            public void put(BudgetCustTranGetDataRowImpl obj, Object value) {
                obj.setBudgetCustomerId((Number)value);
            }
        }
        ,
        BudgetDate {
            public Object get(BudgetCustTranGetDataRowImpl obj) {
                return obj.getBudgetDate();
            }

            public void put(BudgetCustTranGetDataRowImpl obj, Object value) {
                obj.setBudgetDate((Date)value);
            }
        }
        ,
        BudgetType {
            public Object get(BudgetCustTranGetDataRowImpl obj) {
                return obj.getBudgetType();
            }

            public void put(BudgetCustTranGetDataRowImpl obj, Object value) {
                obj.setBudgetType((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(BudgetCustTranGetDataRowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(BudgetCustTranGetDataRowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(BudgetCustTranGetDataRowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(BudgetCustTranGetDataRowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        ModifiedBy {
            public Object get(BudgetCustTranGetDataRowImpl obj) {
                return obj.getModifiedBy();
            }

            public void put(BudgetCustTranGetDataRowImpl obj, Object value) {
                obj.setModifiedBy((String)value);
            }
        }
        ,
        ModifiedDate {
            public Object get(BudgetCustTranGetDataRowImpl obj) {
                return obj.getModifiedDate();
            }

            public void put(BudgetCustTranGetDataRowImpl obj, Object value) {
                obj.setModifiedDate((Date)value);
            }
        }
        ,
        Percentage {
            public Object get(BudgetCustTranGetDataRowImpl obj) {
                return obj.getPercentage();
            }

            public void put(BudgetCustTranGetDataRowImpl obj, Object value) {
                obj.setPercentage((Number)value);
            }
        }
        ,
        Remarks {
            public Object get(BudgetCustTranGetDataRowImpl obj) {
                return obj.getRemarks();
            }

            public void put(BudgetCustTranGetDataRowImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(BudgetCustTranGetDataRowImpl object);

        public abstract void put(BudgetCustTranGetDataRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int AMOUNT = AttributesEnum.Amount.index();
    public static final int BUDGETASTODATE = AttributesEnum.BudgetAsToDate.index();
    public static final int BUDGETCUSTTRANID = AttributesEnum.BudgetCustTranId.index();
    public static final int BUDGETCUSTOMERID = AttributesEnum.BudgetCustomerId.index();
    public static final int BUDGETDATE = AttributesEnum.BudgetDate.index();
    public static final int BUDGETTYPE = AttributesEnum.BudgetType.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int MODIFIEDBY = AttributesEnum.ModifiedBy.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int PERCENTAGE = AttributesEnum.Percentage.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();

    /**
     * This is the default constructor (do not remove).
     */
    public BudgetCustTranGetDataRowImpl() {
    }

    /**
     * Gets BudgetCustTran entity object.
     * @return the BudgetCustTran
     */
    public BudgetCustTranImpl getBudgetCustTran() {
        return (BudgetCustTranImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for AMOUNT using the alias name Amount.
     * @return the AMOUNT
     */
    public Number getAmount() {
        return (Number) getAttributeInternal(AMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for AMOUNT using the alias name Amount.
     * @param value value to set the AMOUNT
     */
    public void setAmount(Number value) {
        setAttributeInternal(AMOUNT, value);
    }

    /**
     * Gets the attribute value for BUDGET_AS_TO_DATE using the alias name BudgetAsToDate.
     * @return the BUDGET_AS_TO_DATE
     */
    public Number getBudgetAsToDate() {
        return (Number) getAttributeInternal(BUDGETASTODATE);
    }

    /**
     * Sets <code>value</code> as attribute value for BUDGET_AS_TO_DATE using the alias name BudgetAsToDate.
     * @param value value to set the BUDGET_AS_TO_DATE
     */
    public void setBudgetAsToDate(Number value) {
        setAttributeInternal(BUDGETASTODATE, value);
    }

    /**
     * Gets the attribute value for BUDGET_CUST_TRAN_ID using the alias name BudgetCustTranId.
     * @return the BUDGET_CUST_TRAN_ID
     */
    public DBSequence getBudgetCustTranId() {
        return (DBSequence)getAttributeInternal(BUDGETCUSTTRANID);
    }

    /**
     * Sets <code>value</code> as attribute value for BUDGET_CUST_TRAN_ID using the alias name BudgetCustTranId.
     * @param value value to set the BUDGET_CUST_TRAN_ID
     */
    public void setBudgetCustTranId(DBSequence value) {
        setAttributeInternal(BUDGETCUSTTRANID, value);
    }

    /**
     * Gets the attribute value for BUDGET_CUSTOMER_ID using the alias name BudgetCustomerId.
     * @return the BUDGET_CUSTOMER_ID
     */
    public Number getBudgetCustomerId() {
        return (Number) getAttributeInternal(BUDGETCUSTOMERID);
    }

    /**
     * Sets <code>value</code> as attribute value for BUDGET_CUSTOMER_ID using the alias name BudgetCustomerId.
     * @param value value to set the BUDGET_CUSTOMER_ID
     */
    public void setBudgetCustomerId(Number value) {
        setAttributeInternal(BUDGETCUSTOMERID, value);
    }

    /**
     * Gets the attribute value for BUDGET_DATE using the alias name BudgetDate.
     * @return the BUDGET_DATE
     */
    public Date getBudgetDate() {
        return (Date) getAttributeInternal(BUDGETDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for BUDGET_DATE using the alias name BudgetDate.
     * @param value value to set the BUDGET_DATE
     */
    public void setBudgetDate(Date value) {
        setAttributeInternal(BUDGETDATE, value);
    }

    /**
     * Gets the attribute value for BUDGET_TYPE using the alias name BudgetType.
     * @return the BUDGET_TYPE
     */
    public String getBudgetType() {
        return (String) getAttributeInternal(BUDGETTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for BUDGET_TYPE using the alias name BudgetType.
     * @param value value to set the BUDGET_TYPE
     */
    public void setBudgetType(String value) {
        setAttributeInternal(BUDGETTYPE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for MODIFIED_BY using the alias name ModifiedBy.
     * @return the MODIFIED_BY
     */
    public String getModifiedBy() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_BY using the alias name ModifiedBy.
     * @param value value to set the MODIFIED_BY
     */
    public void setModifiedBy(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @return the MODIFIED_DATE
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @param value value to set the MODIFIED_DATE
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for PERCENTAGE using the alias name Percentage.
     * @return the PERCENTAGE
     */
    public Number getPercentage() {
        return (Number) getAttributeInternal(PERCENTAGE);
    }

    /**
     * Sets <code>value</code> as attribute value for PERCENTAGE using the alias name Percentage.
     * @param value value to set the PERCENTAGE
     */
    public void setPercentage(Number value) {
        setAttributeInternal(PERCENTAGE, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


}
