package app.fpp.model.views.promoproposal.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 20 08:13:56 ICT 2017
// ---------------------------------------------------------------------
public interface PromoProdukView extends ViewObject {
    void removeCanceledRow();

}
