package app.fpp.model.views.promoproposal;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 12 14:26:10 ICT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DiscountViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DiscountViewImpl() {
    }
}
