package app.fpp.model.views.promoproposal;

import app.fpp.model.entities.promoproposal.PromoProdukImpl;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 30 15:01:27 ICT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PromoProdukViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PromoProdukId {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getPromoProdukId();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setPromoProdukId((DBSequence)value);
            }
        }
        ,
        ProposalId {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getProposalId();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setProposalId((Number)value);
            }
        }
        ,
        ProductCategory {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getProductCategory();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setProductCategory((String)value);
            }
        }
        ,
        ProductCategoryDesc {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getProductCategoryDesc();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setProductCategoryDesc((String)value);
            }
        }
        ,
        ProductClass {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getProductClass();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setProductClass((String)value);
            }
        }
        ,
        ProductClassDesc {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getProductClassDesc();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setProductClassDesc((String)value);
            }
        }
        ,
        ProductBrand {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getProductBrand();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setProductBrand((String)value);
            }
        }
        ,
        ProductBrandDesc {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getProductBrandDesc();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setProductBrandDesc((String)value);
            }
        }
        ,
        ProductExt {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getProductExt();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setProductExt((String)value);
            }
        }
        ,
        ProductExtDesc {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getProductExtDesc();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setProductExtDesc((String)value);
            }
        }
        ,
        ProductPack {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getProductPack();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setProductPack((String)value);
            }
        }
        ,
        ProductPackDesc {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getProductPackDesc();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setProductPackDesc((String)value);
            }
        }
        ,
        Descr {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getDescr();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setDescr((String)value);
            }
        }
        ,
        Mekanisme {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getMekanisme();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setMekanisme((String)value);
            }
        }
        ,
        AmountPromo {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getAmountPromo();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setAmountPromo((Number)value);
            }
        }
        ,
        EstBudgetProp {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getEstBudgetProp();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setEstBudgetProp((Number)value);
            }
        }
        ,
        RegCustFlag {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getRegCustFlag();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setRegCustFlag((String)value);
            }
        }
        ,
        ProductName {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getProductName();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setProductName((String)value);
            }
        }
        ,
        ProductVariant {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getProductVariant();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setProductVariant((String)value);
            }
        }
        ,
        ProductItem {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getProductItem();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setProductItem((String)value);
            }
        }
        ,
        DiscNonYearly {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getDiscNonYearly();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setDiscNonYearly((Number)value);
            }
        }
        ,
        DiscYearly {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getDiscYearly();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setDiscYearly((Number)value);
            }
        }
        ,
        DiscRasioNonYearly {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getDiscRasioNonYearly();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setDiscRasioNonYearly((Number)value);
            }
        }
        ,
        DiscRasioYearly {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getDiscRasioYearly();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setDiscRasioYearly((Number)value);
            }
        }
        ,
        DiscRasioTotal {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getDiscRasioTotal();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setDiscRasioTotal((Number)value);
            }
        }
        ,
        BarangBonusNonYearly {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getBarangBonusNonYearly();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setBarangBonusNonYearly((Number)value);
            }
        }
        ,
        BarangBonusYearly {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getBarangBonusYearly();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setBarangBonusYearly((Number)value);
            }
        }
        ,
        BarangBonusRasioNonYearly {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getBarangBonusRasioNonYearly();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setBarangBonusRasioNonYearly((Number)value);
            }
        }
        ,
        BarangBonusRasioYearly {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getBarangBonusRasioYearly();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setBarangBonusRasioYearly((Number)value);
            }
        }
        ,
        BarangBonusRasioTotal {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getBarangBonusRasioTotal();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setBarangBonusRasioTotal((Number)value);
            }
        }
        ,
        BiayaNonYearly {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getBiayaNonYearly();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setBiayaNonYearly((Number)value);
            }
        }
        ,
        BiayaYearly {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getBiayaYearly();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setBiayaYearly((Number)value);
            }
        }
        ,
        BiayaRasioNonYearly {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getBiayaRasioNonYearly();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setBiayaRasioNonYearly((Number)value);
            }
        }
        ,
        BiayaRasioYearly {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getBiayaRasioYearly();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setBiayaRasioYearly((Number)value);
            }
        }
        ,
        BiayaRasioTotal {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getBiayaRasioTotal();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setBiayaRasioTotal((Number)value);
            }
        }
        ,
        BudgetBy {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getBudgetBy();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setBudgetBy((String)value);
            }
        }
        ,
        KodePosting {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getKodePosting();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setKodePosting((String)value);
            }
        }
        ,
        KodePostingDesc {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getKodePostingDesc();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setKodePostingDesc((String)value);
            }
        }
        ,
        ValidComb {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getValidComb();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setValidComb((String)value);
            }
        }
        ,
        ItemExpense {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getItemExpense();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setItemExpense((String)value);
            }
        }
        ,
        ItemExpenseDesc {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getItemExpenseDesc();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setItemExpenseDesc((String)value);
            }
        }
        ,
        KodePostingMf {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getKodePostingMf();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setKodePostingMf((String)value);
            }
        }
        ,
        KodePostingMfDesc {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getKodePostingMfDesc();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setKodePostingMfDesc((String)value);
            }
        }
        ,
        ProductCombination {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getProductCombination();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setProductCombination((String)value);
            }
        }
        ,
        ExclCustBy {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getExclCustBy();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setExclCustBy((String)value);
            }
        }
        ,
        ExclCustLovParam {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getExclCustLovParam();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setExclCustLovParam((String)value);
            }
        }
        ,
        ProductVarCode {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getProductVarCode();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setProductVarCode((String)value);
            }
        }
        ,
        ProductItemCode {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getProductItemCode();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setProductItemCode((String)value);
            }
        }
        ,
        DiscountView {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getDiscountView();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TargetView {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getTargetView();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ProdukItemView {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getProdukItemView();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ProdukVariantView {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getProdukVariantView();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BiayaView {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getBiayaView();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PromoBonusView {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getPromoBonusView();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ProdRegionView {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getProdRegionView();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ProdRegionCustomerView {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getProdRegionCustomerView();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ProdRegionAreaView {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getProdRegionAreaView();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ProdBudgetByView {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getProdBudgetByView();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ProdBudgetByPostView {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getProdBudgetByPostView();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ProdRegionLocView {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getProdRegionLocView();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ProdRegionCustGroupView {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getProdRegionCustGroupView();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ExclCustAreaView {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getExclCustAreaView();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ExclCustLocView {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getExclCustLocView();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ExclCustRegionView {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getExclCustRegionView();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ExclCustCustView {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getExclCustCustView();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ProductByCategoryLov {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getProductByCategoryLov();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ProductByClassLov {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getProductByClassLov();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ProductByBrandLov {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getProductByBrandLov();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ProductByExtLov {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getProductByExtLov();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ProductByPackagingLov {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getProductByPackagingLov();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CustRegFlagLov {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getCustRegFlagLov();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BudgetByLov {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getBudgetByLov();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        KodePostingLov {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getKodePostingLov();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        KodeItemExpenseLov {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getKodeItemExpenseLov();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ExcludeCustLov {
            public Object get(PromoProdukViewRowImpl obj) {
                return obj.getExcludeCustLov();
            }

            public void put(PromoProdukViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(PromoProdukViewRowImpl object);

        public abstract void put(PromoProdukViewRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PROMOPRODUKID = AttributesEnum.PromoProdukId.index();
    public static final int PROPOSALID = AttributesEnum.ProposalId.index();
    public static final int PRODUCTCATEGORY = AttributesEnum.ProductCategory.index();
    public static final int PRODUCTCATEGORYDESC = AttributesEnum.ProductCategoryDesc.index();
    public static final int PRODUCTCLASS = AttributesEnum.ProductClass.index();
    public static final int PRODUCTCLASSDESC = AttributesEnum.ProductClassDesc.index();
    public static final int PRODUCTBRAND = AttributesEnum.ProductBrand.index();
    public static final int PRODUCTBRANDDESC = AttributesEnum.ProductBrandDesc.index();
    public static final int PRODUCTEXT = AttributesEnum.ProductExt.index();
    public static final int PRODUCTEXTDESC = AttributesEnum.ProductExtDesc.index();
    public static final int PRODUCTPACK = AttributesEnum.ProductPack.index();
    public static final int PRODUCTPACKDESC = AttributesEnum.ProductPackDesc.index();
    public static final int DESCR = AttributesEnum.Descr.index();
    public static final int MEKANISME = AttributesEnum.Mekanisme.index();
    public static final int AMOUNTPROMO = AttributesEnum.AmountPromo.index();
    public static final int ESTBUDGETPROP = AttributesEnum.EstBudgetProp.index();
    public static final int REGCUSTFLAG = AttributesEnum.RegCustFlag.index();
    public static final int PRODUCTNAME = AttributesEnum.ProductName.index();
    public static final int PRODUCTVARIANT = AttributesEnum.ProductVariant.index();
    public static final int PRODUCTITEM = AttributesEnum.ProductItem.index();
    public static final int DISCNONYEARLY = AttributesEnum.DiscNonYearly.index();
    public static final int DISCYEARLY = AttributesEnum.DiscYearly.index();
    public static final int DISCRASIONONYEARLY = AttributesEnum.DiscRasioNonYearly.index();
    public static final int DISCRASIOYEARLY = AttributesEnum.DiscRasioYearly.index();
    public static final int DISCRASIOTOTAL = AttributesEnum.DiscRasioTotal.index();
    public static final int BARANGBONUSNONYEARLY = AttributesEnum.BarangBonusNonYearly.index();
    public static final int BARANGBONUSYEARLY = AttributesEnum.BarangBonusYearly.index();
    public static final int BARANGBONUSRASIONONYEARLY = AttributesEnum.BarangBonusRasioNonYearly.index();
    public static final int BARANGBONUSRASIOYEARLY = AttributesEnum.BarangBonusRasioYearly.index();
    public static final int BARANGBONUSRASIOTOTAL = AttributesEnum.BarangBonusRasioTotal.index();
    public static final int BIAYANONYEARLY = AttributesEnum.BiayaNonYearly.index();
    public static final int BIAYAYEARLY = AttributesEnum.BiayaYearly.index();
    public static final int BIAYARASIONONYEARLY = AttributesEnum.BiayaRasioNonYearly.index();
    public static final int BIAYARASIOYEARLY = AttributesEnum.BiayaRasioYearly.index();
    public static final int BIAYARASIOTOTAL = AttributesEnum.BiayaRasioTotal.index();
    public static final int BUDGETBY = AttributesEnum.BudgetBy.index();
    public static final int KODEPOSTING = AttributesEnum.KodePosting.index();
    public static final int KODEPOSTINGDESC = AttributesEnum.KodePostingDesc.index();
    public static final int VALIDCOMB = AttributesEnum.ValidComb.index();
    public static final int ITEMEXPENSE = AttributesEnum.ItemExpense.index();
    public static final int ITEMEXPENSEDESC = AttributesEnum.ItemExpenseDesc.index();
    public static final int KODEPOSTINGMF = AttributesEnum.KodePostingMf.index();
    public static final int KODEPOSTINGMFDESC = AttributesEnum.KodePostingMfDesc.index();
    public static final int PRODUCTCOMBINATION = AttributesEnum.ProductCombination.index();
    public static final int EXCLCUSTBY = AttributesEnum.ExclCustBy.index();
    public static final int EXCLCUSTLOVPARAM = AttributesEnum.ExclCustLovParam.index();
    public static final int PRODUCTVARCODE = AttributesEnum.ProductVarCode.index();
    public static final int PRODUCTITEMCODE = AttributesEnum.ProductItemCode.index();
    public static final int DISCOUNTVIEW = AttributesEnum.DiscountView.index();
    public static final int TARGETVIEW = AttributesEnum.TargetView.index();
    public static final int PRODUKITEMVIEW = AttributesEnum.ProdukItemView.index();
    public static final int PRODUKVARIANTVIEW = AttributesEnum.ProdukVariantView.index();
    public static final int BIAYAVIEW = AttributesEnum.BiayaView.index();
    public static final int PROMOBONUSVIEW = AttributesEnum.PromoBonusView.index();
    public static final int PRODREGIONVIEW = AttributesEnum.ProdRegionView.index();
    public static final int PRODREGIONCUSTOMERVIEW = AttributesEnum.ProdRegionCustomerView.index();
    public static final int PRODREGIONAREAVIEW = AttributesEnum.ProdRegionAreaView.index();
    public static final int PRODBUDGETBYVIEW = AttributesEnum.ProdBudgetByView.index();
    public static final int PRODBUDGETBYPOSTVIEW = AttributesEnum.ProdBudgetByPostView.index();
    public static final int PRODREGIONLOCVIEW = AttributesEnum.ProdRegionLocView.index();
    public static final int PRODREGIONCUSTGROUPVIEW = AttributesEnum.ProdRegionCustGroupView.index();
    public static final int EXCLCUSTAREAVIEW = AttributesEnum.ExclCustAreaView.index();
    public static final int EXCLCUSTLOCVIEW = AttributesEnum.ExclCustLocView.index();
    public static final int EXCLCUSTREGIONVIEW = AttributesEnum.ExclCustRegionView.index();
    public static final int EXCLCUSTCUSTVIEW = AttributesEnum.ExclCustCustView.index();
    public static final int PRODUCTBYCATEGORYLOV = AttributesEnum.ProductByCategoryLov.index();
    public static final int PRODUCTBYCLASSLOV = AttributesEnum.ProductByClassLov.index();
    public static final int PRODUCTBYBRANDLOV = AttributesEnum.ProductByBrandLov.index();
    public static final int PRODUCTBYEXTLOV = AttributesEnum.ProductByExtLov.index();
    public static final int PRODUCTBYPACKAGINGLOV = AttributesEnum.ProductByPackagingLov.index();
    public static final int CUSTREGFLAGLOV = AttributesEnum.CustRegFlagLov.index();
    public static final int BUDGETBYLOV = AttributesEnum.BudgetByLov.index();
    public static final int KODEPOSTINGLOV = AttributesEnum.KodePostingLov.index();
    public static final int KODEITEMEXPENSELOV = AttributesEnum.KodeItemExpenseLov.index();
    public static final int EXCLUDECUSTLOV = AttributesEnum.ExcludeCustLov.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PromoProdukViewRowImpl() {
    }

    /**
     * Gets PromoProduk entity object.
     * @return the PromoProduk
     */
    public PromoProdukImpl getPromoProduk() {
        return (PromoProdukImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for PROMO_PRODUK_ID using the alias name PromoProdukId.
     * @return the PROMO_PRODUK_ID
     */
    public DBSequence getPromoProdukId() {
        return (DBSequence)getAttributeInternal(PROMOPRODUKID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROMO_PRODUK_ID using the alias name PromoProdukId.
     * @param value value to set the PROMO_PRODUK_ID
     */
    public void setPromoProdukId(DBSequence value) {
        setAttributeInternal(PROMOPRODUKID, value);
    }

    /**
     * Gets the attribute value for PROPOSAL_ID using the alias name ProposalId.
     * @return the PROPOSAL_ID
     */
    public Number getProposalId() {
        return (Number) getAttributeInternal(PROPOSALID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROPOSAL_ID using the alias name ProposalId.
     * @param value value to set the PROPOSAL_ID
     */
    public void setProposalId(Number value) {
        setAttributeInternal(PROPOSALID, value);
    }

    /**
     * Gets the attribute value for PRODUCT_CATEGORY using the alias name ProductCategory.
     * @return the PRODUCT_CATEGORY
     */
    public String getProductCategory() {
        return (String) getAttributeInternal(PRODUCTCATEGORY);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCT_CATEGORY using the alias name ProductCategory.
     * @param value value to set the PRODUCT_CATEGORY
     */
    public void setProductCategory(String value) {
        setAttributeInternal(PRODUCTCATEGORY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProductCategoryDesc.
     * @return the ProductCategoryDesc
     */
    public String getProductCategoryDesc() {
        String productCategory = null;
        String productCategoryDesc = null;
        if (getProductCategory() != null) {
            productCategory = getProductCategory();
            Row[] prodCatRows;
            prodCatRows = this.getProductByCategoryLov().getFilteredRows("SetCategory", productCategory);
            if (prodCatRows.length > 0) {
                productCategoryDesc = (prodCatRows[0].getAttribute("SetCategoryDesc").toString()).toUpperCase();
            }
            return productCategoryDesc;
        } else {
            return (String) getAttributeInternal(PRODUCTCATEGORYDESC);
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProductCategoryDesc.
     * @param value value to set the  ProductCategoryDesc
     */
    public void setProductCategoryDesc(String value) {
        setAttributeInternal(PRODUCTCATEGORYDESC, value);
    }

    /**
     * Gets the attribute value for PRODUCT_CLASS using the alias name ProductClass.
     * @return the PRODUCT_CLASS
     */
    public String getProductClass() {
        return (String) getAttributeInternal(PRODUCTCLASS);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCT_CLASS using the alias name ProductClass.
     * @param value value to set the PRODUCT_CLASS
     */
    public void setProductClass(String value) {
        setAttributeInternal(PRODUCTCLASS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProductClassDesc.
     * @return the ProductClassDesc
     */
    public String getProductClassDesc() {
        String productClass = null;
        String productClassDesc = null;
        if (getProductClass() != null) {
            productClass = getProductClass();
            Row[] prodClassRows;
            prodClassRows = this.getProductByClassLov().getFilteredRows("SetClass", productClass);
            if (prodClassRows.length > 0) {
                productClassDesc = (prodClassRows[0].getAttribute("SetClassDesc").toString()).toUpperCase();
            }
            return productClassDesc;
        } else {
            return (String) getAttributeInternal(PRODUCTCLASSDESC);
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProductClassDesc.
     * @param value value to set the  ProductClassDesc
     */
    public void setProductClassDesc(String value) {
        setAttributeInternal(PRODUCTCLASSDESC, value);
    }

    /**
     * Gets the attribute value for PRODUCT_BRAND using the alias name ProductBrand.
     * @return the PRODUCT_BRAND
     */
    public String getProductBrand() {
        return (String) getAttributeInternal(PRODUCTBRAND);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCT_BRAND using the alias name ProductBrand.
     * @param value value to set the PRODUCT_BRAND
     */
    public void setProductBrand(String value) {
        setAttributeInternal(PRODUCTBRAND, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProductBrandDesc.
     * @return the ProductBrandDesc
     */
    public String getProductBrandDesc() {
        String productBrand = null;
        String productBrandDesc = null;
        if (getProductBrand() != null) {
            productBrand = getProductBrand();
            Row[] prodBrandRows;
            prodBrandRows = this.getProductByBrandLov().getFilteredRows("SetBrand", productBrand);
            if (prodBrandRows.length > 0) {
                productBrandDesc = (prodBrandRows[0].getAttribute("SetBrandDesc").toString()).toUpperCase();
            }
            return productBrandDesc;
        } else {
            return (String) getAttributeInternal(PRODUCTBRANDDESC);
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProductBrandDesc.
     * @param value value to set the  ProductBrandDesc
     */
    public void setProductBrandDesc(String value) {
        setAttributeInternal(PRODUCTBRANDDESC, value);
    }

    /**
     * Gets the attribute value for PRODUCT_EXT using the alias name ProductExt.
     * @return the PRODUCT_EXT
     */
    public String getProductExt() {
        return (String) getAttributeInternal(PRODUCTEXT);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCT_EXT using the alias name ProductExt.
     * @param value value to set the PRODUCT_EXT
     */
    public void setProductExt(String value) {
        setAttributeInternal(PRODUCTEXT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProductExtDesc.
     * @return the ProductExtDesc
     */
    public String getProductExtDesc() {
        String productExt = null;
        String productExtDesc = null;
        if (getProductExt() != null) {
            productExt = getProductExt();
            Row[] prodExtRows;
            prodExtRows = this.getProductByExtLov().getFilteredRows("SetExt", productExt);
            if (prodExtRows.length > 0) {
                productExtDesc = (prodExtRows[0].getAttribute("SetExtDesc").toString()).toUpperCase();
            }
            return productExtDesc;
        } else {
            return (String) getAttributeInternal(PRODUCTEXTDESC);
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProductExtDesc.
     * @param value value to set the  ProductExtDesc
     */
    public void setProductExtDesc(String value) {
        setAttributeInternal(PRODUCTEXTDESC, value);
    }

    /**
     * Gets the attribute value for PRODUCT_PACK using the alias name ProductPack.
     * @return the PRODUCT_PACK
     */
    public String getProductPack() {
        return (String) getAttributeInternal(PRODUCTPACK);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCT_PACK using the alias name ProductPack.
     * @param value value to set the PRODUCT_PACK
     */
    public void setProductPack(String value) {
        setAttributeInternal(PRODUCTPACK, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProductPackDesc.
     * @return the ProductPackDesc
     */
    public String getProductPackDesc() {
        String productPack = null;
        String productPackDesc = null;
        if (getProductPack() != null) {
            productPack = getProductPack();
            Row[] prodPackRows;
            prodPackRows = this.getProductByPackagingLov().getFilteredRows("SetPackaging", productPack);
            if (prodPackRows.length > 0) {
                productPackDesc = (prodPackRows[0].getAttribute("SetPackagingDesc").toString()).toUpperCase();
            }
            return productPackDesc;
        } else {
            return (String) getAttributeInternal(PRODUCTPACKDESC);
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProductPackDesc.
     * @param value value to set the  ProductPackDesc
     */
    public void setProductPackDesc(String value) {
        setAttributeInternal(PRODUCTPACKDESC, value);
    }

    /**
     * Gets the attribute value for DESCR using the alias name Descr.
     * @return the DESCR
     */
    public String getDescr() {
        return (String) getAttributeInternal(DESCR);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCR using the alias name Descr.
     * @param value value to set the DESCR
     */
    public void setDescr(String value) {
        setAttributeInternal(DESCR, value);
    }

    /**
     * Gets the attribute value for MEKANISME using the alias name Mekanisme.
     * @return the MEKANISME
     */
    public String getMekanisme() {
        return (String) getAttributeInternal(MEKANISME);
    }

    /**
     * Sets <code>value</code> as attribute value for MEKANISME using the alias name Mekanisme.
     * @param value value to set the MEKANISME
     */
    public void setMekanisme(String value) {
        setAttributeInternal(MEKANISME, value);
    }

    /**
     * Gets the attribute value for AMOUNT_PROMO using the alias name AmountPromo.
     * @return the AMOUNT_PROMO
     */
    public Number getAmountPromo() {
        return (Number) getAttributeInternal(AMOUNTPROMO);
    }

    /**
     * Sets <code>value</code> as attribute value for AMOUNT_PROMO using the alias name AmountPromo.
     * @param value value to set the AMOUNT_PROMO
     */
    public void setAmountPromo(Number value) {
        setAttributeInternal(AMOUNTPROMO, value);
    }

    /**
     * Gets the attribute value for EST_BUDGET_PROP using the alias name EstBudgetProp.
     * @return the EST_BUDGET_PROP
     */
    public Number getEstBudgetProp() {
        return (Number) getAttributeInternal(ESTBUDGETPROP);
    }

    /**
     * Sets <code>value</code> as attribute value for EST_BUDGET_PROP using the alias name EstBudgetProp.
     * @param value value to set the EST_BUDGET_PROP
     */
    public void setEstBudgetProp(Number value) {
        setAttributeInternal(ESTBUDGETPROP, value);
    }

    /**
     * Gets the attribute value for REG_CUST_FLAG using the alias name RegCustFlag.
     * @return the REG_CUST_FLAG
     */
    public String getRegCustFlag() {
        return (String) getAttributeInternal(REGCUSTFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for REG_CUST_FLAG using the alias name RegCustFlag.
     * @param value value to set the REG_CUST_FLAG
     */
    public void setRegCustFlag(String value) {
        setAttributeInternal(REGCUSTFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProductName.
     * @return the ProductName
     */
    public String getProductName() {
        return (String) getAttributeInternal(PRODUCTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProductName.
     * @param value value to set the  ProductName
     */
    public void setProductName(String value) {
        setAttributeInternal(PRODUCTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProductVariant.
     * @return the ProductVariant
     */
    public String getProductVariant() {
        return (String) getAttributeInternal(PRODUCTVARIANT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProductVariant.
     * @param value value to set the  ProductVariant
     */
    public void setProductVariant(String value) {
        setAttributeInternal(PRODUCTVARIANT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProductItem.
     * @return the ProductItem
     */
    public String getProductItem() {
        return (String) getAttributeInternal(PRODUCTITEM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProductItem.
     * @param value value to set the  ProductItem
     */
    public void setProductItem(String value) {
        setAttributeInternal(PRODUCTITEM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DiscNonYearly.
     * @return the DiscNonYearly
     */
    public Number getDiscNonYearly() {
        return (Number) getAttributeInternal(DISCNONYEARLY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DiscNonYearly.
     * @param value value to set the  DiscNonYearly
     */
    public void setDiscNonYearly(Number value) {
        setAttributeInternal(DISCNONYEARLY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DiscYearly.
     * @return the DiscYearly
     */
    public Number getDiscYearly() {
        return (Number) getAttributeInternal(DISCYEARLY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DiscYearly.
     * @param value value to set the  DiscYearly
     */
    public void setDiscYearly(Number value) {
        setAttributeInternal(DISCYEARLY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DiscRasioNonYearly.
     * @return the DiscRasioNonYearly
     */
    public Number getDiscRasioNonYearly() {
        return (Number) getAttributeInternal(DISCRASIONONYEARLY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DiscRasioNonYearly.
     * @param value value to set the  DiscRasioNonYearly
     */
    public void setDiscRasioNonYearly(Number value) {
        setAttributeInternal(DISCRASIONONYEARLY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DiscRasioYearly.
     * @return the DiscRasioYearly
     */
    public Number getDiscRasioYearly() {
        return (Number) getAttributeInternal(DISCRASIOYEARLY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DiscRasioYearly.
     * @param value value to set the  DiscRasioYearly
     */
    public void setDiscRasioYearly(Number value) {
        setAttributeInternal(DISCRASIOYEARLY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DiscRasioTotal.
     * @return the DiscRasioTotal
     */
    public Number getDiscRasioTotal() {
        return (Number) getAttributeInternal(DISCRASIOTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DiscRasioTotal.
     * @param value value to set the  DiscRasioTotal
     */
    public void setDiscRasioTotal(Number value) {
        setAttributeInternal(DISCRASIOTOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BarangBonusNonYearly.
     * @return the BarangBonusNonYearly
     */
    public Number getBarangBonusNonYearly() {
        return (Number) getAttributeInternal(BARANGBONUSNONYEARLY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BarangBonusNonYearly.
     * @param value value to set the  BarangBonusNonYearly
     */
    public void setBarangBonusNonYearly(Number value) {
        setAttributeInternal(BARANGBONUSNONYEARLY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BarangBonusYearly.
     * @return the BarangBonusYearly
     */
    public Number getBarangBonusYearly() {
        return (Number) getAttributeInternal(BARANGBONUSYEARLY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BarangBonusYearly.
     * @param value value to set the  BarangBonusYearly
     */
    public void setBarangBonusYearly(Number value) {
        setAttributeInternal(BARANGBONUSYEARLY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BarangBonusRasioNonYearly.
     * @return the BarangBonusRasioNonYearly
     */
    public Number getBarangBonusRasioNonYearly() {
        return (Number) getAttributeInternal(BARANGBONUSRASIONONYEARLY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BarangBonusRasioNonYearly.
     * @param value value to set the  BarangBonusRasioNonYearly
     */
    public void setBarangBonusRasioNonYearly(Number value) {
        setAttributeInternal(BARANGBONUSRASIONONYEARLY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BarangBonusRasioYearly.
     * @return the BarangBonusRasioYearly
     */
    public Number getBarangBonusRasioYearly() {
        return (Number) getAttributeInternal(BARANGBONUSRASIOYEARLY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BarangBonusRasioYearly.
     * @param value value to set the  BarangBonusRasioYearly
     */
    public void setBarangBonusRasioYearly(Number value) {
        setAttributeInternal(BARANGBONUSRASIOYEARLY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BarangBonusRasioTotal.
     * @return the BarangBonusRasioTotal
     */
    public Number getBarangBonusRasioTotal() {
        return (Number) getAttributeInternal(BARANGBONUSRASIOTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BarangBonusRasioTotal.
     * @param value value to set the  BarangBonusRasioTotal
     */
    public void setBarangBonusRasioTotal(Number value) {
        setAttributeInternal(BARANGBONUSRASIOTOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BiayaNonYearly.
     * @return the BiayaNonYearly
     */
    public Number getBiayaNonYearly() {
        return (Number) getAttributeInternal(BIAYANONYEARLY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BiayaNonYearly.
     * @param value value to set the  BiayaNonYearly
     */
    public void setBiayaNonYearly(Number value) {
        setAttributeInternal(BIAYANONYEARLY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BiayaYearly.
     * @return the BiayaYearly
     */
    public Number getBiayaYearly() {
        return (Number) getAttributeInternal(BIAYAYEARLY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BiayaYearly.
     * @param value value to set the  BiayaYearly
     */
    public void setBiayaYearly(Number value) {
        setAttributeInternal(BIAYAYEARLY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BiayaRasioNonYearly.
     * @return the BiayaRasioNonYearly
     */
    public Number getBiayaRasioNonYearly() {
        return (Number) getAttributeInternal(BIAYARASIONONYEARLY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BiayaRasioNonYearly.
     * @param value value to set the  BiayaRasioNonYearly
     */
    public void setBiayaRasioNonYearly(Number value) {
        setAttributeInternal(BIAYARASIONONYEARLY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BiayaRasioYearly.
     * @return the BiayaRasioYearly
     */
    public Number getBiayaRasioYearly() {
        return (Number) getAttributeInternal(BIAYARASIOYEARLY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BiayaRasioYearly.
     * @param value value to set the  BiayaRasioYearly
     */
    public void setBiayaRasioYearly(Number value) {
        setAttributeInternal(BIAYARASIOYEARLY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BiayaRasioTotal.
     * @return the BiayaRasioTotal
     */
    public Number getBiayaRasioTotal() {
        return (Number) getAttributeInternal(BIAYARASIOTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BiayaRasioTotal.
     * @param value value to set the  BiayaRasioTotal
     */
    public void setBiayaRasioTotal(Number value) {
        setAttributeInternal(BIAYARASIOTOTAL, value);
    }

    /**
     * Gets the attribute value for BUDGET_BY using the alias name BudgetBy.
     * @return the BUDGET_BY
     */
    public String getBudgetBy() {
        return (String) getAttributeInternal(BUDGETBY);
    }

    /**
     * Sets <code>value</code> as attribute value for BUDGET_BY using the alias name BudgetBy.
     * @param value value to set the BUDGET_BY
     */
    public void setBudgetBy(String value) {
        setAttributeInternal(BUDGETBY, value);
    }

    /**
     * Gets the attribute value for KODE_POSTING using the alias name KodePosting.
     * @return the KODE_POSTING
     */
    public String getKodePosting() {
        return (String) getAttributeInternal(KODEPOSTING);
    }

    /**
     * Sets <code>value</code> as attribute value for KODE_POSTING using the alias name KodePosting.
     * @param value value to set the KODE_POSTING
     */
    public void setKodePosting(String value) {
        setAttributeInternal(KODEPOSTING, value);
    }

    /**
     * Gets the attribute value for the calculated attribute KodePostingDesc.
     * @return the KodePostingDesc
     */
    public String getKodePostingDesc() {
        String kodePosting = null;
        String kodePostingDesc = null;
        if (getKodePosting() != null) {
            kodePosting = getKodePosting();
            Row[] kodePostingRows;
            kodePostingRows = this.getKodePostingLov().getFilteredRows("Item", kodePosting);
            if (kodePostingRows.length > 0) {
                kodePostingDesc = (kodePostingRows[0].getAttribute("ItemDescription").toString()).toUpperCase();
            }
            return kodePostingDesc;
        } else {
            return (String) getAttributeInternal(KODEPOSTINGDESC);
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute KodePostingDesc.
     * @param value value to set the  KodePostingDesc
     */
    public void setKodePostingDesc(String value) {
        setAttributeInternal(KODEPOSTINGDESC, value);
    }

    /**
     * Gets the attribute value for VALID_COMB using the alias name ValidComb.
     * @return the VALID_COMB
     */
    public String getValidComb() {
        return (String) getAttributeInternal(VALIDCOMB);
    }

    /**
     * Sets <code>value</code> as attribute value for VALID_COMB using the alias name ValidComb.
     * @param value value to set the VALID_COMB
     */
    public void setValidComb(String value) {
        setAttributeInternal(VALIDCOMB, value);
    }

    /**
     * Gets the attribute value for ITEM_EXPENSE using the alias name ItemExpense.
     * @return the ITEM_EXPENSE
     */
    public String getItemExpense() {
        return (String) getAttributeInternal(ITEMEXPENSE);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_EXPENSE using the alias name ItemExpense.
     * @param value value to set the ITEM_EXPENSE
     */
    public void setItemExpense(String value) {
        setAttributeInternal(ITEMEXPENSE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ItemExpenseDesc.
     * @return the ItemExpenseDesc
     */
    public String getItemExpenseDesc() {
        String itemExpense = null;
        String itemExpenseDesc = null;
        if (getItemExpense() != null) {
            itemExpense = getItemExpense();
            Row[] itemExpenseRows;
            itemExpenseRows = this.getKodeItemExpenseLov().getFilteredRows("Item", itemExpense);
            if (itemExpenseRows.length > 0) {
                itemExpenseDesc = (itemExpenseRows[0].getAttribute("ItemDescription").toString()).toUpperCase();
            }
            return itemExpenseDesc;
        } else {
            return (String) getAttributeInternal(ITEMEXPENSEDESC);
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ItemExpenseDesc.
     * @param value value to set the  ItemExpenseDesc
     */
    public void setItemExpenseDesc(String value) {
        setAttributeInternal(ITEMEXPENSEDESC, value);
    }

    /**
     * Gets the attribute value for KODE_POSTING_MF using the alias name KodePostingMf.
     * @return the KODE_POSTING_MF
     */
    public String getKodePostingMf() {
        return (String) getAttributeInternal(KODEPOSTINGMF);
    }

    /**
     * Sets <code>value</code> as attribute value for KODE_POSTING_MF using the alias name KodePostingMf.
     * @param value value to set the KODE_POSTING_MF
     */
    public void setKodePostingMf(String value) {
        setAttributeInternal(KODEPOSTINGMF, value);
    }

    /**
     * Gets the attribute value for the calculated attribute KodePostingMfDesc.
     * @return the KodePostingMfDesc
     */
    public String getKodePostingMfDesc() {
        String kodePostingMf = null;
        String kodePostingMfDesc = null;
        if (getKodePostingMf() != null) {
            kodePostingMf = getKodePostingMf();
            Row[] kodePostingMfRows;
            kodePostingMfRows = this.getKodePostingLov().getFilteredRows("Item", kodePostingMf);
            if (kodePostingMfRows.length > 0) {
                kodePostingMfDesc = (kodePostingMfRows[0].getAttribute("ItemDescription").toString()).toUpperCase();
            }
            return kodePostingMfDesc;
        } else {
            return (String) getAttributeInternal(KODEPOSTINGMFDESC);
        }
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute KodePostingMfDesc.
     * @param value value to set the  KodePostingMfDesc
     */
    public void setKodePostingMfDesc(String value) {
        setAttributeInternal(KODEPOSTINGMFDESC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProductCombination.
     * @return the ProductCombination
     */
    public String getProductCombination() {
        return (String) getAttributeInternal(PRODUCTCOMBINATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProductCombination.
     * @param value value to set the  ProductCombination
     */
    public void setProductCombination(String value) {
        setAttributeInternal(PRODUCTCOMBINATION, value);
    }

    /**
     * Gets the attribute value for EXCL_CUST_BY using the alias name ExclCustBy.
     * @return the EXCL_CUST_BY
     */
    public String getExclCustBy() {
        return (String) getAttributeInternal(EXCLCUSTBY);
    }

    /**
     * Sets <code>value</code> as attribute value for EXCL_CUST_BY using the alias name ExclCustBy.
     * @param value value to set the EXCL_CUST_BY
     */
    public void setExclCustBy(String value) {
        setAttributeInternal(EXCLCUSTBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ExclCustLovParam.
     * @return the ExclCustLovParam
     */
    public String getExclCustLovParam() {
        return (String) getAttributeInternal(EXCLCUSTLOVPARAM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ExclCustLovParam.
     * @param value value to set the  ExclCustLovParam
     */
    public void setExclCustLovParam(String value) {
        setAttributeInternal(EXCLCUSTLOVPARAM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProductVarCode.
     * @return the ProductVarCode
     */
    public String getProductVarCode() {
        return (String) getAttributeInternal(PRODUCTVARCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProductVarCode.
     * @param value value to set the  ProductVarCode
     */
    public void setProductVarCode(String value) {
        setAttributeInternal(PRODUCTVARCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProductItemCode.
     * @return the ProductItemCode
     */
    public String getProductItemCode() {
        return (String) getAttributeInternal(PRODUCTITEMCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProductItemCode.
     * @param value value to set the  ProductItemCode
     */
    public void setProductItemCode(String value) {
        setAttributeInternal(PRODUCTITEMCODE, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link DiscountView.
     */
    public RowIterator getDiscountView() {
        return (RowIterator)getAttributeInternal(DISCOUNTVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link TargetView.
     */
    public RowIterator getTargetView() {
        return (RowIterator)getAttributeInternal(TARGETVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ProdukItemView.
     */
    public RowIterator getProdukItemView() {
        return (RowIterator)getAttributeInternal(PRODUKITEMVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ProdukVariantView.
     */
    public RowIterator getProdukVariantView() {
        return (RowIterator)getAttributeInternal(PRODUKVARIANTVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link BiayaView.
     */
    public RowIterator getBiayaView() {
        return (RowIterator)getAttributeInternal(BIAYAVIEW);
    }


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link PromoBonusView.
     */
    public RowIterator getPromoBonusView() {
        return (RowIterator)getAttributeInternal(PROMOBONUSVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ProdRegionView.
     */
    public RowIterator getProdRegionView() {
        return (RowIterator)getAttributeInternal(PRODREGIONVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ProdRegionCustomerView.
     */
    public RowIterator getProdRegionCustomerView() {
        return (RowIterator)getAttributeInternal(PRODREGIONCUSTOMERVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ProdRegionAreaView.
     */
    public RowIterator getProdRegionAreaView() {
        return (RowIterator)getAttributeInternal(PRODREGIONAREAVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ProdBudgetByView.
     */
    public RowIterator getProdBudgetByView() {
        return (RowIterator)getAttributeInternal(PRODBUDGETBYVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ProdBudgetByPostView.
     */
    public RowIterator getProdBudgetByPostView() {
        return (RowIterator)getAttributeInternal(PRODBUDGETBYPOSTVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ProdRegionLocView.
     */
    public RowIterator getProdRegionLocView() {
        return (RowIterator)getAttributeInternal(PRODREGIONLOCVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ProdRegionCustGroupView.
     */
    public RowIterator getProdRegionCustGroupView() {
        return (RowIterator)getAttributeInternal(PRODREGIONCUSTGROUPVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ExclCustAreaView.
     */
    public RowIterator getExclCustAreaView() {
        return (RowIterator)getAttributeInternal(EXCLCUSTAREAVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ExclCustLocView.
     */
    public RowIterator getExclCustLocView() {
        return (RowIterator)getAttributeInternal(EXCLCUSTLOCVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ExclCustRegionView.
     */
    public RowIterator getExclCustRegionView() {
        return (RowIterator)getAttributeInternal(EXCLCUSTREGIONVIEW);
    }


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ExclCustCustView.
     */
    public RowIterator getExclCustCustView() {
        return (RowIterator)getAttributeInternal(EXCLCUSTCUSTVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ProductByCategoryLov.
     */
    public RowSet getProductByCategoryLov() {
        return (RowSet)getAttributeInternal(PRODUCTBYCATEGORYLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ProductByClassLov.
     */
    public RowSet getProductByClassLov() {
        return (RowSet)getAttributeInternal(PRODUCTBYCLASSLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ProductByBrandLov.
     */
    public RowSet getProductByBrandLov() {
        return (RowSet)getAttributeInternal(PRODUCTBYBRANDLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ProductByExtLov.
     */
    public RowSet getProductByExtLov() {
        return (RowSet)getAttributeInternal(PRODUCTBYEXTLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ProductByPackagingLov.
     */
    public RowSet getProductByPackagingLov() {
        return (RowSet)getAttributeInternal(PRODUCTBYPACKAGINGLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CustRegFlagLov.
     */
    public RowSet getCustRegFlagLov() {
        return (RowSet)getAttributeInternal(CUSTREGFLAGLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BudgetByLov.
     */
    public RowSet getBudgetByLov() {
        return (RowSet)getAttributeInternal(BUDGETBYLOV);
    }


    /**
     * Gets the view accessor <code>RowSet</code> KodePostingLov.
     */
    public RowSet getKodePostingLov() {
        return (RowSet)getAttributeInternal(KODEPOSTINGLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> KodeItemExpenseLov.
     */
    public RowSet getKodeItemExpenseLov() {
        return (RowSet)getAttributeInternal(KODEITEMEXPENSELOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ExcludeCustLov.
     */
    public RowSet getExcludeCustLov() {
        return (RowSet)getAttributeInternal(EXCLUDECUSTLOV);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
