package app.fpp.model.am.client;

import app.fpp.model.am.common.BudgetSettingAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 05 09:52:47 ICT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BudgetSettingAMClient extends ApplicationModuleImpl implements BudgetSettingAM {
    /**
     * This is the default constructor (do not remove).
     */
    public BudgetSettingAMClient() {
    }

    public void setLoginToSession_BudgetSettingAM(String key, String val) {
        Object _ret =
            this.riInvokeExportedMethod(this,"setLoginToSession_BudgetSettingAM",new String [] {"java.lang.String","java.lang.String"},new Object[] {key, val});
        return;
    }
}
