package app.fpp.model.am.client;

import app.fpp.model.am.common.DashboardAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 19 13:12:34 ICT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DashboardAMClient extends ApplicationModuleImpl implements DashboardAM {
    /**
     * This is the default constructor (do not remove).
     */
    public DashboardAMClient() {
    }

    public void setLoginToSession_DashboardAM(String key, String val) {
        Object _ret =
            this.riInvokeExportedMethod(this,"setLoginToSession_DashboardAM",new String [] {"java.lang.String","java.lang.String"},new Object[] {key, val});
        return;
    }
}
