package app.fpp.model.entities.confirmation.targetpr;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 05 15:22:46 ICT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FcsPoRequisitionTempImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CreationDate {
            public Object get(FcsPoRequisitionTempImpl obj) {
                return obj.getCreationDate();
            }

            public void put(FcsPoRequisitionTempImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        InterfaceSourceCode {
            public Object get(FcsPoRequisitionTempImpl obj) {
                return obj.getInterfaceSourceCode();
            }

            public void put(FcsPoRequisitionTempImpl obj, Object value) {
                obj.setInterfaceSourceCode((String)value);
            }
        }
        ,
        SourceTypeCode {
            public Object get(FcsPoRequisitionTempImpl obj) {
                return obj.getSourceTypeCode();
            }

            public void put(FcsPoRequisitionTempImpl obj, Object value) {
                obj.setSourceTypeCode((String)value);
            }
        }
        ,
        RequisitionType {
            public Object get(FcsPoRequisitionTempImpl obj) {
                return obj.getRequisitionType();
            }

            public void put(FcsPoRequisitionTempImpl obj, Object value) {
                obj.setRequisitionType((String)value);
            }
        }
        ,
        DestinationTypeCode {
            public Object get(FcsPoRequisitionTempImpl obj) {
                return obj.getDestinationTypeCode();
            }

            public void put(FcsPoRequisitionTempImpl obj, Object value) {
                obj.setDestinationTypeCode((String)value);
            }
        }
        ,
        UnitPrice {
            public Object get(FcsPoRequisitionTempImpl obj) {
                return obj.getUnitPrice();
            }

            public void put(FcsPoRequisitionTempImpl obj, Object value) {
                obj.setUnitPrice((Number)value);
            }
        }
        ,
        AuthorizationStatus {
            public Object get(FcsPoRequisitionTempImpl obj) {
                return obj.getAuthorizationStatus();
            }

            public void put(FcsPoRequisitionTempImpl obj, Object value) {
                obj.setAuthorizationStatus((String)value);
            }
        }
        ,
        BatchId {
            public Object get(FcsPoRequisitionTempImpl obj) {
                return obj.getBatchId();
            }

            public void put(FcsPoRequisitionTempImpl obj, Object value) {
                obj.setBatchId((Number)value);
            }
        }
        ,
        GroupCode {
            public Object get(FcsPoRequisitionTempImpl obj) {
                return obj.getGroupCode();
            }

            public void put(FcsPoRequisitionTempImpl obj, Object value) {
                obj.setGroupCode((String)value);
            }
        }
        ,
        ApprovalPathId {
            public Object get(FcsPoRequisitionTempImpl obj) {
                return obj.getApprovalPathId();
            }

            public void put(FcsPoRequisitionTempImpl obj, Object value) {
                obj.setApprovalPathId((Number)value);
            }
        }
        ,
        PreparerName {
            public Object get(FcsPoRequisitionTempImpl obj) {
                return obj.getPreparerName();
            }

            public void put(FcsPoRequisitionTempImpl obj, Object value) {
                obj.setPreparerName((String)value);
            }
        }
        ,
        ReqNumberSegment1 {
            public Object get(FcsPoRequisitionTempImpl obj) {
                return obj.getReqNumberSegment1();
            }

            public void put(FcsPoRequisitionTempImpl obj, Object value) {
                obj.setReqNumberSegment1((String)value);
            }
        }
        ,
        HeaderAttribute1 {
            public Object get(FcsPoRequisitionTempImpl obj) {
                return obj.getHeaderAttribute1();
            }

            public void put(FcsPoRequisitionTempImpl obj, Object value) {
                obj.setHeaderAttribute1((String)value);
            }
        }
        ,
        HeaderAttribute2 {
            public Object get(FcsPoRequisitionTempImpl obj) {
                return obj.getHeaderAttribute2();
            }

            public void put(FcsPoRequisitionTempImpl obj, Object value) {
                obj.setHeaderAttribute2((String)value);
            }
        }
        ,
        HeaderAttribute3 {
            public Object get(FcsPoRequisitionTempImpl obj) {
                return obj.getHeaderAttribute3();
            }

            public void put(FcsPoRequisitionTempImpl obj, Object value) {
                obj.setHeaderAttribute3((String)value);
            }
        }
        ,
        HeaderAttribute4 {
            public Object get(FcsPoRequisitionTempImpl obj) {
                return obj.getHeaderAttribute4();
            }

            public void put(FcsPoRequisitionTempImpl obj, Object value) {
                obj.setHeaderAttribute4((String)value);
            }
        }
        ,
        ItemSegment1 {
            public Object get(FcsPoRequisitionTempImpl obj) {
                return obj.getItemSegment1();
            }

            public void put(FcsPoRequisitionTempImpl obj, Object value) {
                obj.setItemSegment1((String)value);
            }
        }
        ,
        UnitOfMeasure {
            public Object get(FcsPoRequisitionTempImpl obj) {
                return obj.getUnitOfMeasure();
            }

            public void put(FcsPoRequisitionTempImpl obj, Object value) {
                obj.setUnitOfMeasure((String)value);
            }
        }
        ,
        UomCode {
            public Object get(FcsPoRequisitionTempImpl obj) {
                return obj.getUomCode();
            }

            public void put(FcsPoRequisitionTempImpl obj, Object value) {
                obj.setUomCode((String)value);
            }
        }
        ,
        Quantity {
            public Object get(FcsPoRequisitionTempImpl obj) {
                return obj.getQuantity();
            }

            public void put(FcsPoRequisitionTempImpl obj, Object value) {
                obj.setQuantity((Number)value);
            }
        }
        ,
        LineType {
            public Object get(FcsPoRequisitionTempImpl obj) {
                return obj.getLineType();
            }

            public void put(FcsPoRequisitionTempImpl obj, Object value) {
                obj.setLineType((String)value);
            }
        }
        ,
        NoteToReceiver {
            public Object get(FcsPoRequisitionTempImpl obj) {
                return obj.getNoteToReceiver();
            }

            public void put(FcsPoRequisitionTempImpl obj, Object value) {
                obj.setNoteToReceiver((String)value);
            }
        }
        ,
        DestinationOrganizationCode {
            public Object get(FcsPoRequisitionTempImpl obj) {
                return obj.getDestinationOrganizationCode();
            }

            public void put(FcsPoRequisitionTempImpl obj, Object value) {
                obj.setDestinationOrganizationCode((String)value);
            }
        }
        ,
        DestinationSubinventory {
            public Object get(FcsPoRequisitionTempImpl obj) {
                return obj.getDestinationSubinventory();
            }

            public void put(FcsPoRequisitionTempImpl obj, Object value) {
                obj.setDestinationSubinventory((String)value);
            }
        }
        ,
        DeliverToLocationCode {
            public Object get(FcsPoRequisitionTempImpl obj) {
                return obj.getDeliverToLocationCode();
            }

            public void put(FcsPoRequisitionTempImpl obj, Object value) {
                obj.setDeliverToLocationCode((String)value);
            }
        }
        ,
        DeliverToRequestorName {
            public Object get(FcsPoRequisitionTempImpl obj) {
                return obj.getDeliverToRequestorName();
            }

            public void put(FcsPoRequisitionTempImpl obj, Object value) {
                obj.setDeliverToRequestorName((String)value);
            }
        }
        ,
        DistributionAttribute1 {
            public Object get(FcsPoRequisitionTempImpl obj) {
                return obj.getDistributionAttribute1();
            }

            public void put(FcsPoRequisitionTempImpl obj, Object value) {
                obj.setDistributionAttribute1((String)value);
            }
        }
        ,
        OrgId {
            public Object get(FcsPoRequisitionTempImpl obj) {
                return obj.getOrgId();
            }

            public void put(FcsPoRequisitionTempImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        LineNum {
            public Object get(FcsPoRequisitionTempImpl obj) {
                return obj.getLineNum();
            }

            public void put(FcsPoRequisitionTempImpl obj, Object value) {
                obj.setLineNum((Number)value);
            }
        }
        ,
        PrId {
            public Object get(FcsPoRequisitionTempImpl obj) {
                return obj.getPrId();
            }

            public void put(FcsPoRequisitionTempImpl obj, Object value) {
                obj.setPrId((DBSequence)value);
            }
        }
        ,
        Status {
            public Object get(FcsPoRequisitionTempImpl obj) {
                return obj.getStatus();
            }

            public void put(FcsPoRequisitionTempImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        LineAttribute2 {
            public Object get(FcsPoRequisitionTempImpl obj) {
                return obj.getLineAttribute2();
            }

            public void put(FcsPoRequisitionTempImpl obj, Object value) {
                obj.setLineAttribute2((String)value);
            }
        }
        ,
        Revision {
            public Object get(FcsPoRequisitionTempImpl obj) {
                return obj.getRevision();
            }

            public void put(FcsPoRequisitionTempImpl obj, Object value) {
                obj.setRevision((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(FcsPoRequisitionTempImpl object);

        public abstract void put(FcsPoRequisitionTempImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int INTERFACESOURCECODE = AttributesEnum.InterfaceSourceCode.index();
    public static final int SOURCETYPECODE = AttributesEnum.SourceTypeCode.index();
    public static final int REQUISITIONTYPE = AttributesEnum.RequisitionType.index();
    public static final int DESTINATIONTYPECODE = AttributesEnum.DestinationTypeCode.index();
    public static final int UNITPRICE = AttributesEnum.UnitPrice.index();
    public static final int AUTHORIZATIONSTATUS = AttributesEnum.AuthorizationStatus.index();
    public static final int BATCHID = AttributesEnum.BatchId.index();
    public static final int GROUPCODE = AttributesEnum.GroupCode.index();
    public static final int APPROVALPATHID = AttributesEnum.ApprovalPathId.index();
    public static final int PREPARERNAME = AttributesEnum.PreparerName.index();
    public static final int REQNUMBERSEGMENT1 = AttributesEnum.ReqNumberSegment1.index();
    public static final int HEADERATTRIBUTE1 = AttributesEnum.HeaderAttribute1.index();
    public static final int HEADERATTRIBUTE2 = AttributesEnum.HeaderAttribute2.index();
    public static final int HEADERATTRIBUTE3 = AttributesEnum.HeaderAttribute3.index();
    public static final int HEADERATTRIBUTE4 = AttributesEnum.HeaderAttribute4.index();
    public static final int ITEMSEGMENT1 = AttributesEnum.ItemSegment1.index();
    public static final int UNITOFMEASURE = AttributesEnum.UnitOfMeasure.index();
    public static final int UOMCODE = AttributesEnum.UomCode.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int LINETYPE = AttributesEnum.LineType.index();
    public static final int NOTETORECEIVER = AttributesEnum.NoteToReceiver.index();
    public static final int DESTINATIONORGANIZATIONCODE = AttributesEnum.DestinationOrganizationCode.index();
    public static final int DESTINATIONSUBINVENTORY = AttributesEnum.DestinationSubinventory.index();
    public static final int DELIVERTOLOCATIONCODE = AttributesEnum.DeliverToLocationCode.index();
    public static final int DELIVERTOREQUESTORNAME = AttributesEnum.DeliverToRequestorName.index();
    public static final int DISTRIBUTIONATTRIBUTE1 = AttributesEnum.DistributionAttribute1.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int LINENUM = AttributesEnum.LineNum.index();
    public static final int PRID = AttributesEnum.PrId.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int LINEATTRIBUTE2 = AttributesEnum.LineAttribute2.index();
    public static final int REVISION = AttributesEnum.Revision.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FcsPoRequisitionTempImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("app.fpp.model.entities.confirmation.targetpr.FcsPoRequisitionTemp");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for InterfaceSourceCode, using the alias name InterfaceSourceCode.
     * @return the InterfaceSourceCode
     */
    public String getInterfaceSourceCode() {
        return (String)getAttributeInternal(INTERFACESOURCECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for InterfaceSourceCode.
     * @param value value to set the InterfaceSourceCode
     */
    public void setInterfaceSourceCode(String value) {
        setAttributeInternal(INTERFACESOURCECODE, value);
    }

    /**
     * Gets the attribute value for SourceTypeCode, using the alias name SourceTypeCode.
     * @return the SourceTypeCode
     */
    public String getSourceTypeCode() {
        return (String)getAttributeInternal(SOURCETYPECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SourceTypeCode.
     * @param value value to set the SourceTypeCode
     */
    public void setSourceTypeCode(String value) {
        setAttributeInternal(SOURCETYPECODE, value);
    }

    /**
     * Gets the attribute value for RequisitionType, using the alias name RequisitionType.
     * @return the RequisitionType
     */
    public String getRequisitionType() {
        return (String)getAttributeInternal(REQUISITIONTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for RequisitionType.
     * @param value value to set the RequisitionType
     */
    public void setRequisitionType(String value) {
        setAttributeInternal(REQUISITIONTYPE, value);
    }

    /**
     * Gets the attribute value for DestinationTypeCode, using the alias name DestinationTypeCode.
     * @return the DestinationTypeCode
     */
    public String getDestinationTypeCode() {
        return (String)getAttributeInternal(DESTINATIONTYPECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DestinationTypeCode.
     * @param value value to set the DestinationTypeCode
     */
    public void setDestinationTypeCode(String value) {
        setAttributeInternal(DESTINATIONTYPECODE, value);
    }

    /**
     * Gets the attribute value for UnitPrice, using the alias name UnitPrice.
     * @return the UnitPrice
     */
    public Number getUnitPrice() {
        return (Number)getAttributeInternal(UNITPRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UnitPrice.
     * @param value value to set the UnitPrice
     */
    public void setUnitPrice(Number value) {
        setAttributeInternal(UNITPRICE, value);
    }

    /**
     * Gets the attribute value for AuthorizationStatus, using the alias name AuthorizationStatus.
     * @return the AuthorizationStatus
     */
    public String getAuthorizationStatus() {
        return (String)getAttributeInternal(AUTHORIZATIONSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for AuthorizationStatus.
     * @param value value to set the AuthorizationStatus
     */
    public void setAuthorizationStatus(String value) {
        setAttributeInternal(AUTHORIZATIONSTATUS, value);
    }

    /**
     * Gets the attribute value for BatchId, using the alias name BatchId.
     * @return the BatchId
     */
    public Number getBatchId() {
        return (Number)getAttributeInternal(BATCHID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BatchId.
     * @param value value to set the BatchId
     */
    public void setBatchId(Number value) {
        setAttributeInternal(BATCHID, value);
    }

    /**
     * Gets the attribute value for GroupCode, using the alias name GroupCode.
     * @return the GroupCode
     */
    public String getGroupCode() {
        return (String)getAttributeInternal(GROUPCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for GroupCode.
     * @param value value to set the GroupCode
     */
    public void setGroupCode(String value) {
        setAttributeInternal(GROUPCODE, value);
    }

    /**
     * Gets the attribute value for ApprovalPathId, using the alias name ApprovalPathId.
     * @return the ApprovalPathId
     */
    public Number getApprovalPathId() {
        return (Number)getAttributeInternal(APPROVALPATHID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ApprovalPathId.
     * @param value value to set the ApprovalPathId
     */
    public void setApprovalPathId(Number value) {
        setAttributeInternal(APPROVALPATHID, value);
    }

    /**
     * Gets the attribute value for PreparerName, using the alias name PreparerName.
     * @return the PreparerName
     */
    public String getPreparerName() {
        return (String)getAttributeInternal(PREPARERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for PreparerName.
     * @param value value to set the PreparerName
     */
    public void setPreparerName(String value) {
        setAttributeInternal(PREPARERNAME, value);
    }

    /**
     * Gets the attribute value for ReqNumberSegment1, using the alias name ReqNumberSegment1.
     * @return the ReqNumberSegment1
     */
    public String getReqNumberSegment1() {
        return (String)getAttributeInternal(REQNUMBERSEGMENT1);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReqNumberSegment1.
     * @param value value to set the ReqNumberSegment1
     */
    public void setReqNumberSegment1(String value) {
        setAttributeInternal(REQNUMBERSEGMENT1, value);
    }

    /**
     * Gets the attribute value for HeaderAttribute1, using the alias name HeaderAttribute1.
     * @return the HeaderAttribute1
     */
    public String getHeaderAttribute1() {
        return (String)getAttributeInternal(HEADERATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for HeaderAttribute1.
     * @param value value to set the HeaderAttribute1
     */
    public void setHeaderAttribute1(String value) {
        setAttributeInternal(HEADERATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for HeaderAttribute2, using the alias name HeaderAttribute2.
     * @return the HeaderAttribute2
     */
    public String getHeaderAttribute2() {
        return (String)getAttributeInternal(HEADERATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for HeaderAttribute2.
     * @param value value to set the HeaderAttribute2
     */
    public void setHeaderAttribute2(String value) {
        setAttributeInternal(HEADERATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for HeaderAttribute4, using the alias name HeaderAttribute4.
     * @return the HeaderAttribute4
     */
    public String getHeaderAttribute4() {
        return (String)getAttributeInternal(HEADERATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for HeaderAttribute4.
     * @param value value to set the HeaderAttribute4
     */
    public void setHeaderAttribute4(String value) {
        setAttributeInternal(HEADERATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ItemSegment1, using the alias name ItemSegment1.
     * @return the ItemSegment1
     */
    public String getItemSegment1() {
        return (String)getAttributeInternal(ITEMSEGMENT1);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemSegment1.
     * @param value value to set the ItemSegment1
     */
    public void setItemSegment1(String value) {
        setAttributeInternal(ITEMSEGMENT1, value);
    }

    /**
     * Gets the attribute value for UnitOfMeasure, using the alias name UnitOfMeasure.
     * @return the UnitOfMeasure
     */
    public String getUnitOfMeasure() {
        return (String)getAttributeInternal(UNITOFMEASURE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UnitOfMeasure.
     * @param value value to set the UnitOfMeasure
     */
    public void setUnitOfMeasure(String value) {
        setAttributeInternal(UNITOFMEASURE, value);
    }

    /**
     * Gets the attribute value for UomCode, using the alias name UomCode.
     * @return the UomCode
     */
    public String getUomCode() {
        return (String)getAttributeInternal(UOMCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UomCode.
     * @param value value to set the UomCode
     */
    public void setUomCode(String value) {
        setAttributeInternal(UOMCODE, value);
    }

    /**
     * Gets the attribute value for Quantity, using the alias name Quantity.
     * @return the Quantity
     */
    public Number getQuantity() {
        return (Number)getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Quantity.
     * @param value value to set the Quantity
     */
    public void setQuantity(Number value) {
        setAttributeInternal(QUANTITY, value);
    }

    /**
     * Gets the attribute value for LineType, using the alias name LineType.
     * @return the LineType
     */
    public String getLineType() {
        return (String)getAttributeInternal(LINETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineType.
     * @param value value to set the LineType
     */
    public void setLineType(String value) {
        setAttributeInternal(LINETYPE, value);
    }

    /**
     * Gets the attribute value for NoteToReceiver, using the alias name NoteToReceiver.
     * @return the NoteToReceiver
     */
    public String getNoteToReceiver() {
        return (String)getAttributeInternal(NOTETORECEIVER);
    }

    /**
     * Sets <code>value</code> as the attribute value for NoteToReceiver.
     * @param value value to set the NoteToReceiver
     */
    public void setNoteToReceiver(String value) {
        setAttributeInternal(NOTETORECEIVER, value);
    }

    /**
     * Gets the attribute value for DestinationOrganizationCode, using the alias name DestinationOrganizationCode.
     * @return the DestinationOrganizationCode
     */
    public String getDestinationOrganizationCode() {
        return (String)getAttributeInternal(DESTINATIONORGANIZATIONCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DestinationOrganizationCode.
     * @param value value to set the DestinationOrganizationCode
     */
    public void setDestinationOrganizationCode(String value) {
        setAttributeInternal(DESTINATIONORGANIZATIONCODE, value);
    }

    /**
     * Gets the attribute value for DestinationSubinventory, using the alias name DestinationSubinventory.
     * @return the DestinationSubinventory
     */
    public String getDestinationSubinventory() {
        return (String)getAttributeInternal(DESTINATIONSUBINVENTORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for DestinationSubinventory.
     * @param value value to set the DestinationSubinventory
     */
    public void setDestinationSubinventory(String value) {
        setAttributeInternal(DESTINATIONSUBINVENTORY, value);
    }

    /**
     * Gets the attribute value for DeliverToLocationCode, using the alias name DeliverToLocationCode.
     * @return the DeliverToLocationCode
     */
    public String getDeliverToLocationCode() {
        return (String)getAttributeInternal(DELIVERTOLOCATIONCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeliverToLocationCode.
     * @param value value to set the DeliverToLocationCode
     */
    public void setDeliverToLocationCode(String value) {
        setAttributeInternal(DELIVERTOLOCATIONCODE, value);
    }

    /**
     * Gets the attribute value for DeliverToRequestorName, using the alias name DeliverToRequestorName.
     * @return the DeliverToRequestorName
     */
    public String getDeliverToRequestorName() {
        return (String)getAttributeInternal(DELIVERTOREQUESTORNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeliverToRequestorName.
     * @param value value to set the DeliverToRequestorName
     */
    public void setDeliverToRequestorName(String value) {
        setAttributeInternal(DELIVERTOREQUESTORNAME, value);
    }

    /**
     * Gets the attribute value for DistributionAttribute1, using the alias name DistributionAttribute1.
     * @return the DistributionAttribute1
     */
    public String getDistributionAttribute1() {
        return (String)getAttributeInternal(DISTRIBUTIONATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for DistributionAttribute1.
     * @param value value to set the DistributionAttribute1
     */
    public void setDistributionAttribute1(String value) {
        setAttributeInternal(DISTRIBUTIONATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for OrgId, using the alias name OrgId.
     * @return the OrgId
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgId.
     * @param value value to set the OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for LineNum, using the alias name LineNum.
     * @return the LineNum
     */
    public Number getLineNum() {
        return (Number)getAttributeInternal(LINENUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineNum.
     * @param value value to set the LineNum
     */
    public void setLineNum(Number value) {
        setAttributeInternal(LINENUM, value);
    }

    /**
     * Gets the attribute value for PrId, using the alias name PrId.
     * @return the PrId
     */
    public DBSequence getPrId() {
        return (DBSequence)getAttributeInternal(PRID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PrId.
     * @param value value to set the PrId
     */
    public void setPrId(DBSequence value) {
        setAttributeInternal(PRID, value);
    }

    /**
     * Gets the attribute value for Status, using the alias name Status.
     * @return the Status
     */
    public String getStatus() {
        return (String)getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Status.
     * @param value value to set the Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for LineAttribute2, using the alias name LineAttribute2.
     * @return the LineAttribute2
     */
    public String getLineAttribute2() {
        return (String)getAttributeInternal(LINEATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineAttribute2.
     * @param value value to set the LineAttribute2
     */
    public void setLineAttribute2(String value) {
        setAttributeInternal(LINEATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Revision, using the alias name Revision.
     * @return the Revision
     */
    public Number getRevision() {
        return (Number)getAttributeInternal(REVISION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Revision.
     * @param value value to set the Revision
     */
    public void setRevision(Number value) {
        setAttributeInternal(REVISION, value);
    }

    /**
     * Gets the attribute value for HeaderAttribute3, using the alias name HeaderAttribute3.
     * @return the HeaderAttribute3
     */
    public String getHeaderAttribute3() {
        return (String)getAttributeInternal(HEADERATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for HeaderAttribute3.
     * @param value value to set the HeaderAttribute3
     */
    public void setHeaderAttribute3(String value) {
        setAttributeInternal(HEADERATTRIBUTE3, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


    /**
     * @param prId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(DBSequence prId) {
        return new Key(new Object[]{prId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        SequenceImpl seq = new SequenceImpl("APPS.FCS_PO_REQUISITION_TEMP_S", getDBTransaction());
        this.setPrId(new DBSequence(seq.getSequenceNumber()));
    }
}
